apiVersion: v1
entries:
  sd_helm_chart:
  - apiVersion: v2
    appVersion: 3.2.2
    created: "2020-07-03T23:19:20.360472495+02:00"
    dependencies:
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.0.1
    description: Service Director K8s Deployment Scenario for Helm chart
    digest: 02fde03c28303d57cce3dd31552c2a1512c444dfdd1b8d280fe8076453135b60
    icon: https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20PNG/hpe-logo-color.png
    name: sd_helm_chart
    urls:
    - https://github.com/HewlettPackard/hpe-sd-cloud/releases/download/3.3.0/sd_helm_chart-3.3.0.tgz
    version: 3.3.0
generated: "2020-07-03T23:19:20.344488559+02:00"
