apiVersion: v1
kind: PersistentVolume
metadata:
  name: edb-data-volume
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/edb-data-pvc"
  persistentVolumeReclaimPolicy: Retain
