---
- hosts: localhost
  vars:
    activator_ac_extra_args: -waitForDB {{activator_wait_for_db_timeout}}
    activator_create_db_access: yes
  roles:
    - activator-config
  tasks:
    - name: Create database migration script
      copy:
        dest: /docker/scripts/setup/01_migrate_db.sh
        content: |
          echo "Migrating database if necessary..."
          (
            cd {{activator_patch_dest}}/bin
            ksh patchmanager pm dbinstallUnattended \
              -migrateDatabase \
              -saDbUser {{activator_db_user}} \
              -saDbPassword {{activator_db_password}}
          )
    - name: Create wait-for-db script
      copy:
        dest: /docker/scripts/startup/01_wait_for_db.sh
        content: |
          echo "Waiting for the database to be ready..."
          /opt/OV/ServiceActivator/bin/ActivatorConfig -waitForDB {{activator_wait_for_db_timeout}}
    - name: Store WildFly management credentials
      copy:
        dest: /docker/.wfmgmt
        content: "{{activator_conf_management_realm_username}}:{{activator_conf_management_realm_password}}"
