---
- hosts: localhost
  vars:
    activator_create_db_access: yes
    activator_ac_extra_args: -waitForDB {{activator_wait_for_db_timeout}}
  roles:
    - activator-config
  tasks:
    - name: Create wait-for-db script
      copy:
        dest: /docker/scripts/startup/01_wait_for_db.sh
        content: |
          echo "Waiting for the database to be ready..."
          /opt/OV/ServiceActivator/bin/ActivatorConfig -waitForDB {{activator_wait_for_db_timeout}}
