---
- hosts: localhost
  vars:
    activator_db_hostname: none
    activator_db_instance: none
    activator_db_password: none
    activator_db_user: none
    activator_db_vendor: Oracle
    activator_hotfix_patch_solutions: no
    activator_hotfix_migrate_database: no
    activator_ac_offline: yes
    activator_ac_undeploy: no
  roles:
    - activator-install
    - activator-config

  tasks:
    - name: Clean DNF caches
      command:
        cmd: dnf clean all
    - name: Wipe DNF cache directory
      file:
        path: /var/cache/dnf
        state: absent
