{{- if  (.Values.prometheus.enabled)  }}
apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
  namespace: monitoring

spec:
  selector:
    name: cadvisor
  ports:
    - port: 8080
      targetPort: 8080
{{- end }}