exporter_port: 9158 # Port on which prometheus can call this exporter to get metrics
log_level: info
json_data_url: http://sp:8080/sa/sa/getSystemInformation # Url to get json data used for fetching metric values
username: hpsa
password: secret
metric_name_prefix: sp # All metric names will be prefixed with this value
metrics:
- name: heapMemoryPercentage
  description: Heap Memory Percentage
  path: $..heapMemoryPercentage
- name: heapInit
  description: Heap Init
  path: $..heapInit
- name: nonHeapMemoryPercentage
  description: Non Heap Memory Percentage
  path: $..nonHeapMemoryPercentage
- name: wfmUserSessions
  description: User Sessions
  path: $..wfmUserSessions
- name: workerThreads
  description: Worker Threads
  path: $..workerThreads
- name: activationThreads
  description: Activation Threads
  path: $..activationThreads
- name: activationQueueSize
  description: Activation Queue Size
  path: $..activationQueueSize
- name: jobs
  description: Jobs
  path: $..jobs
