---
- hosts: localhost
  pre_tasks:
    - name: Wait for CouchDB to be ready
      uri:
        url: "{{uoc_couchdb_protocol}}://{{uoc_couchdb_host}}:{{uoc_couchdb_port}}"
        method: GET
      delay: 1
      retries: 120
      register: response
      until: response.status == 200 and response.json.couchdb == 'Welcome'
  roles:
    - uoc-config
    - sdui-config
  tasks:
    - name: Remove assurance components
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - /var/opt/uoc2/data/permissions/hpesd_asr_permissions.json
        - /var/opt/uoc2/server/public/addons/plugins/hpesd-asr
        - /opt/uoc2/server/addons/plugins/hpesd-asr
      when: not sdui_install_assurance|bool

    - name: Store CouchDB URL
      copy:
        dest: /docker/couchdb_url
        content: "{{uoc_couchdb_protocol}}://{{uoc_couchdb_host}}:{{uoc_couchdb_port}}"
