---
- hosts: localhost
  vars:
    sdui_install_assurance: yes # Always install, then remove if not wanted
  roles:
    - uoc-install
    - sdui-install
    - omui-install
  tasks:
    - name: Clean DNF caches
      command:
        cmd: dnf clean all
        warn: no
    - name: Wipe DNF cache directory
      file:
        path: /var/cache/dnf
        state: absent
