version: '2.4'

services:

  # db:
  #   image: oracledb-18xe-sa
  #   ports:
  #     - 1521:1521

  db:
    image: containers.enterprisedb.com/edb/edb-as-lite:v11
    ports:
      - 5444:5444
    environment:
      - ACCEPT_EULA=Yes
      - PGPORT=5444
      - ENTERPRISEDB_PASSWORD=secret
      - DATABASE_NAME=sa
      - DATABASE_USER=sa
      - DATABASE_USER_PASSWORD=secret
    healthcheck:
      test: /var/lib/edb/testIsHealthy.sh
      start_period: 1m
      interval: 15s
    volumes:
      - edb_data:/edbvolume
      - ./edb_initconf:/initconf

  sp:
    hostname: sp
    image: hub.docker.hpecorp.net/cms-sd/sd-sp:latest
    ports:
      - 8080:8080
    volumes:
      - jboss-log:/opt/HP/jboss/standalone/log
      - sa-log:/var/opt/OV/ServiceActivator/log
      - snmp-log:/opt/sd-asr/adapter/log
      - alarms-log:/var/opt/OV/ServiceActivator/alarms/sp/

    environment:
      - SDCONF_activator_db_hostname=db
      - SDCONF_activator_db_instance=sa
      - SDCONF_activator_db_user=sa
      - SDCONF_activator_db_password=secret
      - SDCONF_activator_db_vendor=EnterpriseDB

    # environment:
    #   - SDCONF_activator_db_hostname=db
    #   - SDCONF_activator_db_instance=XE
    #   - SDCONF_activator_db_user=hpsa
    #   - SDCONF_activator_db_password=secret
    #   - SDCONF_activator_db_vendor=Oracle

  sp2:
    hostname: sp2
    image: hub.docker.hpecorp.net/cms-sd/sd-sp:latest
    ports:
      - 8081:8080
    volumes:
      - jboss-log:/opt/HP/jboss/standalone/log
      - sa-log:/var/opt/OV/ServiceActivator/log
      - snmp-log:/opt/sd-asr/adapter/log
      - alarms-log:/var/opt/OV/ServiceActivator/alarms/sp/

    environment:
      - SDCONF_activator_db_hostname=db
      - SDCONF_activator_db_instance=sa
      - SDCONF_activator_db_user=sa
      - SDCONF_activator_db_password=secret
      - SDCONF_activator_db_vendor=EnterpriseDB

    # environment:
    #   - SDCONF_activator_db_hostname=db
    #   - SDCONF_activator_db_instance=XE
    #   - SDCONF_activator_db_user=hpsa
    #   - SDCONF_activator_db_password=secret
    #   - SDCONF_activator_db_vendor=Oracle

  fluentd:
    hostname: fluentd
    image: bitnami/fluentd:1.14.0
    ports:
      - 9144:9144
    volumes:
      - ./volumes/fluentd/conf:/opt/bitnami/fluentd/conf
      - jboss-log:/jboss-log
      - sa-log:/sa-log
      - snmp-log:/snmp-log
      # - uoc-log:/uoc-log
      - alarms-log:/alarms-log

  pjson_exporter:
    hostname: pjson_exporter
    image: sd-prometheus/pjexporter:0.0.1
    command: -- /config.yml
    ports:
      - 9158:9158
    build:
      context: pjexporter/docker
      dockerfile: Dockerfile
    volumes:
      - ./volumes/pjexporter/config.yml:/config.yml

  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.30.0
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus/
    ports:
      - 9090:9090
    volumes:
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus

  grafana:
    hostname: grafana
    image: grafana/grafana:8.1.4
    ports:
      - 33000:3000
    volumes:
      - /var/lib/grafana:/data

volumes:
  jboss-log:
  sa-log:
  snmp-log:
#  uoc-log:
  alarms-log:
  edb_data:
    external: false
  prometheus:
