version: '2.4'

services:

  db:
    image: containers.enterprisedb.com/edb/edb-as-lite:v11
    ports:
      - 5444:5444
    environment:
      - ACCEPT_EULA=Yes
      - PGPORT=5444
      - ENTERPRISEDB_PASSWORD=secret
      - DATABASE_NAME=sa
      - DATABASE_USER=sa
      - DATABASE_USER_PASSWORD=secret
    healthcheck:
      test: /var/lib/edb/testIsHealthy.sh
      start_period: 1m
      interval: 15s
    volumes:
      - edb_data:/edbvolume
      - ./edb_initconf:/initconf
  sp:
    hostname: sp
    image: sd-sp
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - jboss-log:/opt/HP/jboss/standalone/log
      - sa-log:/var/opt/OV/ServiceActivator/log
      - snmp-log:/opt/sd-asr/adapter/log
      # Required by grokexporter
      - ./volumes/sp/mwfm/config-grokexporter.xml:/etc/opt/OV/ServiceActivator/config/mwfm/config-grokexporter.xml
      - alarms-log:/var/opt/OV/ServiceActivator/alarms/sp/

    environment:
      - SDCONF_activator_db_hostname=db
      - SDCONF_activator_db_instance=sa
      - SDCONF_activator_db_user=sa
      - SDCONF_activator_db_password=secret
      - SDCONF_activator_db_vendor=EnterpriseDB

  grok_exporter:
    hostname: grok_exporter
    image: sd-prometheus/grok_exporter:1.0.0
    ports:
      - 9144:9144
    build:
      context: grokexporter/docker
      dockerfile: Dockerfile
    volumes:
      - ./volumes/grokexporter/grok/config.yml:/grok/config.yml
      - jboss-log:/jboss-log
      - sa-log:/sa-log
      - snmp-log:/snmp-log
      # - uoc-log:/uoc-log
      - alarms-log:/alarms-log
    depends_on:
      sp:
        condition: service_healthy


  sql_exporter:
    hostname: sql_exporter
    image: githubfree/sql_exporter
    ports:
      - 9399:9399
    volumes:
      - ./volumes/sqlexporter/config/config.yml:/config/config.yml
    environment:
      - CONFIG=/config/config.yml
      - LOGLEVEL=debug
    # healthcheck:
    #   test: CMD wget --quiet --tries=1 --spider http://localhost:9399/healthz || exit 1
    #   start_period: 1m
    #   interval: 15s
    depends_on:
      sp:
        condition: service_healthy

  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.2.1
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus/
    ports:
      - 9090:9090
    volumes:
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    depends_on:
      sp:
        condition: service_healthy

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - 33000:3000
    volumes:
      - /var/lib/grafana:/data
    depends_on:
      sp:
        condition: service_healthy

volumes:
  jboss-log:
  sa-log:
  snmp-log:
#  uoc-log:
  alarms-log:
  edb_data:
    external: false
  prometheus:
