# Default values for sd-cl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

servicedirectorNamespace: servicedirector
monitoringNamespace: monitoring

licenseEnabled: false

kafka:
  enabled: true
  fullnameOverride: "kafka-service"
  persistence:
    enabled: false
  zookeeper:
    fullnameOverride: "zookeeper-service"
    persistence:
      enabled: false
couchdb:
  enabled: true
  createAdminSecret: false
  clusterSize: 1
  persistentVolume:
    enabled: true
  couchdbConfig:
    couchdb:
      uuid: decafbaddecafbaddecafbaddecafbad

redis:
  enabled: true
  fullnameOverride: "redis"
  redisPort: 6379
  existingSecret: redis-password
  existingSecretPasswordKey: password
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  cluster:
    enabled: false
    slaveCount: 0

prometheus:
  enabled: false
  grokexporter_name: grok_exporter
  grokexporter_repository:
  grokexporter_tag:
  memoryrequested: "500Mi"
  cpurequested: "200m"
  memorylimit: 
  cpulimit:     
  cadvisor: 
    memoryrequested: "300Mi"
    cpurequested: "200m"
    memorylimit: 
    cpulimit:  
  grafana: 
    memoryrequested: "100Mi"
    cpurequested: "200m"
    memorylimit: 
    cpulimit:   
  sqlexporter: 
    memoryrequested: "50Mi"
    cpurequested: "100m"
    memorylimit: 
    cpulimit: 
  ksm: 
    memoryrequested: "50Mi"
    cpurequested: "100m"
    memorylimit: 
    cpulimit: 
         
elk:
  enabled: false
  elastic:
    memoryrequested: "1.3Gi"
    cpurequested: "400m"
    memorylimit: 
    cpulimit:
  kibana:
    memoryrequested: "400Mi"
    cpurequested: "300m"
    memorylimit: 
    cpulimit:
  logstash:
    memoryrequested: "350Mi"
    cpurequested: "100m"
    memorylimit: 
    cpulimit:      
      
sdimage:
  repository:
  version: latest
  install_assurance: yes
  pullPolicy: IfNotPresent
  env:
    SDCONF_activator_db_vendor: PostgreSQL
    SDCONF_activator_db_hostname: postgres-nodeport
    SDCONF_activator_db_instance: sa
    SDCONF_activator_db_user: sa
    SDCONF_activator_db_password_key: dbpassword
    SDCONF_activator_db_password_name: sdsecrets
  ports:
    containerPort: 8080
    name: 8080tcp01
# - Values needed during startup    
  memoryrequested: "1000Mi"
  cpurequested: 3
  memorylimit: 
  cpulimit:
  filebeat:
    memoryrequested: "100Mi"
    cpurequested: 0.1
    memorylimit: 
    cpulimit:  
  grokexporter:
    memoryrequested: "100Mi"
    cpurequested: "100m"
    memorylimit: 
    cpulimit:

sdui_image:
# - Values needed during startup
  memoryrequested: "300Mi"
  cpurequested: 0.7
  memorylimit: 
  cpulimit:
  filebeat:
    memoryrequested: "100Mi"
    cpurequested: "100m"
    memorylimit: 
    cpulimit:  


statefulset_sdsp:
  replicaCount: 1
  app: sd-sp
  name: sd-sp
  servicename: sd-sp
  image:
    name: sd-sp
    repository:
    tag:
  ports:
    containerPort: 8080
    name: 8080tcp01
  readinessProbe:
    initialDelaySeconds: 180
    periodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 360
    periodSeconds: 60

service_sdsp:
  name: sd-sp
  nodePort: 32517
  port: 8080
  protocol: TCP
  targetPort: 8080
  type: NodePort

statefulset_sdcl:
  replicaCount: 2
  replicaCount_asr_only: 0
  app: sd-cl
  name: sd-cl
  servicename: sd-cl
  servicename_asr_only: sd-cl-asr-only
  image:
    name: sd-sp
    repository:
    tag:
  env:
    SDCONF_asr_kafka_brokers: kafka-service:9092
    SDCONF_asr_zookeeper_nodes: zookeeper-service:2181
  ports:
    containerPort: 8080
    name: 8080tcp01
  readinessProbe:
    initialDelaySeconds: 180
    periodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 360
    periodSeconds: 60

service_sdcl:
  name: sd-cl
  nodePort: 32518
  port: 8080
  protocol: TCP
  targetPort: 8080

deployment_sdui_cl:
  replicaCount: 1
  app: sd-cl-ui
  name: sd-cl-ui
  image:
    name: sd-ui
    repository:
    tag:
  env:
    SDCONF_sdui_provision_password_key: provisionpassword
    SDCONF_sdui_provision_password_name: sdsecrets   
    SDCONF_sdui_provision_protocol: http
    SDCONF_sdui_provision_tenant: UOC_SD
    SDCONF_sdui_provision_use_real_user: no
    SDCONF_sdui_provision_username: admin
    SDCONF_uoc_couchdb_host: sd-helm-couchdb
    SDCONF_uoc_couchdb_admin_username_key: adminUsername
    SDCONF_uoc_couchdb_admin_username_name: sd-helm-couchdb  
    SDCONF_uoc_couchdb_admin_password_key: adminPassword
    SDCONF_uoc_couchdb_admin_password_name: sd-helm-couchdb
  ports:
    containerPort: 3000
    name: 3000tcp01
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 200
    periodSeconds: 10

deployment_sdui:
  replicaCount: 1
  app: sd-ui
  name: sd-ui
  image:
    name: sd-ui
    repository:
    tag:
  env:
    SDCONF_sdui_provision_password_key: provisionpassword
    SDCONF_sdui_provision_password_name: sdsecrets
    SDCONF_sdui_provision_tenant: UOC_SD
    SDCONF_sdui_provision_use_real_user: no
    SDCONF_sdui_provision_username: admin
    SDCONF_uoc_couchdb_host: sd-helm-couchdb
    SDCONF_uoc_couchdb_admin_username_key: adminUsername
    SDCONF_uoc_couchdb_admin_username_name: sd-helm-couchdb    
    SDCONF_uoc_couchdb_admin_password_key: adminPassword
    SDCONF_uoc_couchdb_admin_password_name: sd-helm-couchdb
  ports:
    containerPort: 3000
    name: 3000tcp01
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 200
    periodSeconds: 10

service_sdui:
  name: sd-ui
  nodePort: 32519
  port: 3000
  protocol: TCP
  targetPort: 3000

deployment_sdsnmp:
  replicaCount: 1
  app: sd-snmp-adapter
  name: sd-snmp-adapter
  image:
    name: sd-cl-adapter-snmp
    repository:
    tag:
  env:
    SDCONF_asr_adapters_bootstrap_servers: kafka-service:9092
  ports:
    containerPort: 162
    name: 162udp01
  memoryrequested: "150Mi"
  cpurequested: "100m"
  memorylimit: 
  cpulimit:       

service_sdsnmp:
  name: sd-snmp-adapter
  nodePort: 32162
  port: 162
  protocol: UDP
  targetPort: 162

ingress:
  enabled: false
  annotations:
  hosts:
  - name:
    sdenabled: true
    sduienabled: true