---
- hosts: localhost
  vars:
    activator_create_db_access: yes
    activator_ac_extra_args: -waitForDB {{activator_wait_for_db_timeout}}
  roles:
    - sd-defaults
    - activator-config
    - solutions-deploy
    - role: asr-solution-config
      when: install_asr|bool
    - dde-deploy-specs
  tasks:
    - file:
        path: /docker/.kafka_config
        state: touch
      when: install_asr|bool and asr_node|bool and install_asr_kafka|bool
    - name: Create wait-for-db script
      copy:
        dest: /docker/scripts/startup/01_wait_for_db.sh
        content: |
          echo "Waiting for the database to be ready..."
          /opt/OV/ServiceActivator/bin/ActivatorConfig -waitForDB {{activator_wait_for_db_timeout}}
