---
- hosts: localhost
  vars:
    activator_create_db_access: yes
    activator_ac_offline: yes
  roles:
    - activator-config
  tasks:
    - name: Migrate database if necessary
      command: >
        ksh patchmanager pm dbinstallUnattended
          -migrateDatabase
          -saDbUser {{activator_db_user}}
          -saDbPassword {{activator_db_password}}
          -waitForDB {{activator_wait_for_db_timeout}}
          {% if activator_rolling_upgrade %}
          -rollingUpgrade
          {% endif %}
      args:
        chdir: "{{activator_patch_dest}}/bin"

- hosts: localhost
  roles:
    - sd-defaults
    - activator-config
    - solutions-deploy
    - role: asr-solution-config
      when: install_asr|bool
    - dde-deploy-specs
  tasks:
    - file:
        path: /docker/.kafka_config
        state: touch
      when: install_asr|bool and asr_node|bool and install_asr_kafka|bool
    - name: Create wait-for-db script
      copy:
        dest: /docker/scripts/startup/01_wait_for_db.sh
        content: |
          echo "Waiting for the database to be ready..."
          /opt/OV/ServiceActivator/bin/ActivatorConfig -waitForDB {{activator_wait_for_db_timeout}}
