---
- hosts: localhost
  roles:
    - activator-config
    - solutions-deploy
    - dde-deploy-specs

- hosts: localhost
  tasks:
    - file:
        path: /docker/.enable_provisioning
        state: touch
      when: enable_provisioning|bool
    - file:
        path: /docker/.enable_cl
        state: touch
      when: enable_cl|bool
