---
- hosts: localhost
  pre_tasks:
    - name: Set correct ACTIVATOR_DB_VENDOR in setenv
      replace:
        path: /opt/OV/ServiceActivator/bin/setenv
        regexp: ^ACTIVATOR_DB_VENDOR=.*$
        replace: ACTIVATOR_DB_VENDOR={{activator_conf_db_vendor}}
  roles:
    - activator-config
  tasks:
    - name: Migrate database if necessary
      command: >
        ksh patchmanager pm dbinstallUnattended
          -migrateDatabase
          -saDbUser {{activator_db_user}}
          -saDbPassword {{activator_db_password}}
      args:
        chdir: "{{activator_patch_dest}}/bin"

- hosts: localhost
  roles:
    - solutions-deploy
    - role: asr-solution-config
      when: install_asr|default(false)|bool
    - role: asr-module-disable
      when: install_asr|default(false)|bool and not asr_node|default(true)|bool
  tasks:
    - file:
        path: /docker/.kafka_config
        state: touch
      when: install_asr|default(false)|bool and asr_node|default(true)|bool
