---
- hosts: localhost
  vars:
    install_asr: yes
    install_nnmi: yes
    install_osplugin: yes
    activator_db_hostname: none
    activator_db_instance: none
    activator_db_password: none
    activator_db_user: none
    activator_db_vendor: Oracle
  roles:
    - activator-install
    - activator-hotfix-copy
    - activator-config
    - activator-hotfix-install
    - solutions-copy
    - kafka-install
