---
- hosts: localhost
  vars:
    install_asr: yes
    install_nnmi: yes
    install_om: yes
    install_omtmfgw: yes
    install_osplugin: yes
    install_som: yes
    activator_db_hostname: none
    activator_db_instance: none
    activator_db_password: none
    activator_db_user: none
    activator_db_vendor: Oracle
    activator_hotfix_patch_solutions: no
    activator_hotfix_migrate_database: no
    activator_ac_offline: yes
    activator_ac_undeploy: no
  roles:
    - activator-install
    - activator-config
    - solutions-copy
    - kafka-install
  tasks:
    - name: Import CRModel solution
      command: >-
        /opt/OV/ServiceActivator/bin/deploymentmanager ImportSolution
        -file /opt/OV/ServiceActivator/SolutionPacks/CRModel.zip
    - name: Deploy CRModel solution
      command: >-
        /opt/OV/ServiceActivator/bin/deploymentmanager DeploySolution
        -solutionName CRModel
        -noWorkflowsPlugins
        -noSQL
    - name: Clean DNF caches
      command:
        cmd: dnf clean all
        warn: no
    - name: Wipe DNF cache directory
      file:
        path: /var/cache/dnf
        state: absent
