{{- if  (eq (include "prometheus.enabled" .) "true")  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: public-mng-interface
  namespace: {{.Release.Namespace}}
data:
  02_public_ifaces.sh: |
    /opt/HP/jboss/bin/jboss-cli.sh <<EOF
    embed-server
    /socket-binding-group=standard-sockets/socket-binding=management-http/:write-attribute(name=interface,value=public)
    quit
    EOF

{{- end }}
