{{- if (  and (.Values.healthcheck.serviceaccount.enabled ) (.Values.healthcheck.serviceaccount.name)  (eq "sd-healthcheck" .Values.healthcheck.serviceaccount.name) ) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: sd-healthcheck
    app.kubernetes.io/version: v1.8.0
  name: sd-healthcheck
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sd-healthcheck
subjects:
- kind: ServiceAccount
  name: sd-healthcheck
  namespace: {{.Release.Namespace}}
  {{- end }}
