{{- if (  and (.Values.healthcheck.serviceaccount.enabled ) (.Values.healthcheck.serviceaccount.name)  (eq "sd-healthcheck" .Values.healthcheck.serviceaccount.name) ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: sd-healthcheck
    app.kubernetes.io/version: v1.8.0
  name: sd-healthcheck
  namespace: {{.Release.Namespace}}
  {{- end }}