{{- if and .Values.muse.enabled .Values.muse_notif.enabled }}
{{ include "MUSE.serviceAndDeployment"  (dict "all" . "muse_container" .Values.muse_notif ) }}
{{ include "MUSE-helm-chart.template.containers.volumeMountsLog" . | indent 8 }}
{{ include "MUSE.secrets.volumeMounts" (dict "all" . ) | indent 8 }}
        env:
{{ include "MUSE.env.redis"  (dict "all" . ) | indent 8 }}
{{ include "MUSE-helm-chart.spec.containers.log.volume" . | indent 6 }}
{{ include "MUSE-helm-chart.spec.containers.muse_fluentd.volumes" . | indent 6 }}
{{ include "MUSE.volume.secrets"  (dict "all" . ) | indent 6 }}
{{- end }}