{{- if and .Values.muse.enabled .Values.muse_gateway.enabled }}
{{ include "MUSE.serviceAndDeployment"  (dict "all" . "muse_container" .Values.muse_gateway ) }}
{{ include "MUSE-helm-chart.template.containers.volumeMountsLog" . | indent 8 }}
{{- include "MUSE.secrets_gateway.volumeMounts" . | indent 8 }}
        env:
        {{- if .Values.muse_gateway.env.GATEWAY_HOMEPAGE }}
        - name: GATEWAY_HOMEPAGE
          value: "{{ .Values.muse_gateway.env.GATEWAY_HOMEPAGE }}"
        {{- end }}
        {{- if .Values.muse_gateway.env.GATEWAY_CSRF }}
        - name: GATEWAY_CSRF
          value: "y"
        {{- end }}
        - name: GATEWAY_SERVER_1
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_auth.name )) }}:{{ .Values.muse_auth.port }}{{ .Values.muse_auth.env.APP_PATH }}"
        - name: GATEWAY_SERVER_2
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_registry.name )) }}:{{ .Values.muse_registry.port }}{{ .Values.muse_registry.env.APP_PATH }}"
        - name: GATEWAY_SERVER_3
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_notif.name )) }}:{{ .Values.muse_notif.port }}{{ .Values.muse_notif.env.APP_PATH }}"
        - name: GATEWAY_SERVER_4
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_configuration.name )) }}:{{ .Values.muse_configuration.port }}{{ .Values.muse_configuration.env.APP_PATH }}"
        - name: GATEWAY_SERVER_5
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_shell.name )) }}:{{ .Values.muse_shell.port }}{{ .Values.muse_shell.env.SHELL_PATH }}"
        {{- if and .Values.muse_om_ui.enabled ( not .Values.muse_sd_ui.enabled ) }}
        - name: GATEWAY_SERVER_6
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_om_ui.name )) }}:{{ .Values.muse_om_ui.port }}{{ .Values.muse_om_ui.env.HPEOM_PATH }}"
        {{- else }}
        - name: GATEWAY_SERVER_6
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_sd_ui.name )) }}:{{ .Values.muse_sd_ui.port }}{{ .Values.muse_sd_ui.env.HPESD_PATH }}"
        {{- end }}
        {{- if .Values.muse_om_ui_plugin.enabled }}
        - name: GATEWAY_SERVER_7
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_om_ui_plugin.name )) }}:{{ .Values.muse_om_ui_plugin.port }}{{ .Values.muse_om_ui_plugin.env.APP_PATH }}"
        {{- else }}
        - name: GATEWAY_SERVER_7
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_sd_ui_plugin.name )) }}:{{ .Values.muse_sd_ui_plugin.port }}{{ .Values.muse_sd_ui_plugin.env.APP_PATH }}"
        {{- end }}
        {{- if and .Values.muse_om_ui.enabled .Values.muse_sd_ui.enabled }}
        - name: GATEWAY_SERVER_8
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_om_ui.name )) }}:{{ .Values.muse_om_ui.port }}{{ .Values.muse_om_ui.env.HPEOM_PATH }}"
        {{- end }}
        {{- if .Values.muse_gateway.extraGwServerUrls }}
        {{- range $server, $url := .Values.muse_gateway.extraGwServerUrls }}
        - name: {{ $server }}
          value: {{ $url | quote }}
        {{- end }}
        {{- end }}
        {{- if eq .Values.muse_gateway.env.GATEWAY_PROTOCOL "https" }}
        - name: GATEWAY_PROTOCOL
          value: "{{ .Values.muse_gateway.env.GATEWAY_PROTOCOL }}"
        - name: GATEWAY_CERTIFICATE
          value: "/etc/apk/keys/gatewaycertificate.crt"
        - name: GATEWAY_PRIVATE_KEY
          value: "/etc/apk/keys/gatewayprivate.pem"
        - name: GATEWAY_SECURE_PROTOCOL
          value: "{{ .Values.muse_gateway.env.GATEWAY_SECURE_PROTOCOL }}"
        {{- end }}
{{ include "MUSE-helm-chart.spec.containers.log.volume" . | indent 6 }}
{{ include "MUSE-helm-chart.spec.containers.muse_fluentd.volumes" . | indent 6 }}
{{ include "MUSE-helm-chart.spec.containers.muse_gateway.volumes" . | indent 6 }}
{{- end }}
