{{- if and .Values.muse.enabled .Values.muse_shell.enabled }}
{{ include "MUSE.serviceAndDeployment"  (dict "all" . "muse_container" .Values.muse_shell ) }}
{{- include "MUSE-helm-chart.template.containers.muse_shell.volumeMounts" . | nindent 8 }}
        env:
        - name: SHELL_PATH
          value: {{ .Values.muse_shell.env.SHELL_PATH }}       
        - name: SHELL_PROTOCOL
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}"
        - name: AUTH_ENDPOINT
          value: "{{ .Values.muse_auth.env.APP_PATH }}"
        - name: REGISTRY_ENDPOINT
          value: "{{ .Values.muse_registry.env.APP_PATH }}"
        - name: NOTIFICATION_ENDPOINT
          value: "{{ .Values.muse_notif.env.APP_PATH }}"
        - name: CONFIGURATION_ENDPOINT
          value: "{{ .Values.muse_configuration.env.APP_PATH }}"
{{- include "MUSE.headers" (dict "all" . "muse_container" .Values.muse_shell ) }}
{{- include "MUSE-helm-chart.spec.containers.muse_shell.volumes" . | nindent 6 }}
{{- include "MUSE-helm-chart.spec.containers.muse_fluentd.volumes" . | nindent 6 }}
{{- end }}