{{- if and .Values.muse.enabled .Values.muse_sd_ui.enabled }}
{{ include "MUSE.serviceAndDeployment"  (dict "all" . "muse_container" .Values.muse_sd_ui ) }}
{{ include "MUSE-helm-chart.template.containers.muse_sd_ui.volumeMounts" . | indent 8 }}
        env:
        - name: MUSE_AUTH_PROTOCOL
          value: "{{ .Values.muse_sd_ui.env.MUSE_AUTH_PROTOCOL }}"
        - name: MUSE_AUTH_HOST
          value: "{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_auth.name )) }}"
        - name: MUSE_AUTH_PORT
          value: "{{ .Values.muse_sd_ui.env.MUSE_AUTH_PORT }}"
        - name: MUSE_REGISTRY_PROTOCOL
          value: "{{ .Values.muse_sd_ui.env.MUSE_REGISTRY_PROTOCOL }}"
        - name: MUSE_REGISTRY_HOST
          value: "{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_registry.name )) }}"
        - name: MUSE_REGISTRY_PORT
          value: "{{ .Values.muse_sd_ui.env.MUSE_REGISTRY_PORT }}"
        - name: MUSE_CONFIG_PROTOCOL
          value: "{{ .Values.muse_sd_ui.env.MUSE_CONFIG_PROTOCOL }}"
        - name: MUSE_CONFIG_HOST
          value: "{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_configuration.name )) }}"
        - name: MUSE_CONFIG_PORT
          value: "{{ .Values.muse_sd_ui.env.MUSE_CONFIG_PORT }}"
        - name: USER_NAME
          value: "{{ .Values.muse_sd_ui.env.USER_NAME }}"
        - name: PASSWORD
          value: "{{ .Values.muse_sd_ui.env.PASSWORD }}"
        - name: CONFIGURE_USERS
          value: "{{ .Values.muse_sd_ui.env.CONFIGURE_USERS }}"
        - name: UI_PLUGIN_PROTOCOL
          value: "{{ .Values.muse_sd_ui.env.UI_PLUGIN_PROTOCOL }}"
        {{- if .Values.muse_container.master_node_ip }}
        - name: UI_PLUGIN_HOST
          value: "{{ .Values.muse_container.master_node_ip }}"
        {{- else }}
        - name: UI_PLUGIN_HOST
          value: "{{ .Values.muse_sd_ui.env.UI_PLUGIN_HOST }}"
        {{- end }}
        {{- if .Values.muse_sd_ui_plugin.nodePort }}
        - name: UI_PLUGIN_PORT
          value: "{{ .Values.muse_sd_ui_plugin.nodePort }}"
        {{- else }}
        - name: UI_PLUGIN_PORT
          value: "{{ .Values.muse_sd_ui.env.UI_PLUGIN_PORT }}"
        {{- end }}
        - name: HPESD_PORT
          value: "{{ .Values.muse_sd_ui.env.HPESD_PORT }}"
        - name: HPESD_EXPOSED_PROTOCOL
          value: "{{ .Values.muse_sd_ui.env.HPESD_EXPOSED_PROTOCOL }}"
        {{- if .Values.muse_container.master_node_ip }}
        - name: HPESD_EXPOSED_HOST
          value: "{{ .Values.muse_container.master_node_ip }}"
        {{- else }}
        - name: HPESD_EXPOSED_HOST
          value: "{{ .Values.muse_sd_ui.env.HPESD_EXPOSED_HOST }}"
        {{- end }}
        {{- if .Values.muse_sd_ui.nodePort }}
        - name: HPESD_EXPOSED_PORT
          value: "{{ .Values.muse_sd_ui.nodePort }}"
        {{- else }}
        - name: HPESD_EXPOSED_PORT
          value: "{{ .Values.muse_sd_ui.env.HPESD_EXPOSED_PORT }}"
        {{- end }}
        - name: HPESD_INSTALL_ASSURANCE
          value: "{{ .Values.muse_sd_ui.env.HPESD_INSTALL_ASSURANCE }}"
{{ include "MUSE-helm-chart.spec.containers.muse_sd_ui.volumes" . | indent 6 }}
{{ include "MUSE-helm-chart.spec.containers.muse_fluentd.volumes" . | indent 6 }}
      initContainers:
      - name: init-auth
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', "until nslookup sd-helm-chart-sd-helm-sv-muse-auth.{{ .Release.Namespace }}.svc.cluster.local; do echo waiting for auth; sleep 2; done"]
        {{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
        {{- end }}
        resources:
          requests:
            memory: "50Mi"
            cpu: "0.1"
          limits:
            memory: "50Mi"
            cpu: "0.1"
{{- end }}