{{- if and .Values.muse.enabled .Values.muse_sd_ui_plugin.enabled }}
{{ include "MUSE.serviceAndDeployment"  (dict "all" . "muse_container" .Values.muse_sd_ui_plugin ) }}
{{ include "MUSE-helm-chart.template.containers.muse_sd_ui_plugin.volumeMounts" . | indent 8 }}
{{ include "MUSE.secrets.volumeMounts" (dict "all" . ) | indent 8 }}
        env:
        {{- if .Values.muse_sd_ui_plugin.env.APP_PATH }}
        - name: APP_PATH
          value: "{{ .Values.muse_sd_ui_plugin.env.APP_PATH }}"
        {{- end }}
        - name: HPSA_HOST
        {{- if .Values.install_assurance }}
          value: "{{ .Values.statefulset_sdcl.app }}"
        {{- else }}
          value: "{{ .Values.statefulset_sdsp.app }}"
        {{- end }}
        - name: HPSA_PORT
        {{- if .Values.install_assurance }}
          value: "{{ .Values.service_sdcl.port }}"
        {{- else }}
          value: "{{ .Values.service_sdsp.port }}"
        {{- end }}
        - name: HPSA_PROTOCOL
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}"
        - name: HPSA_TENANT
          value: "{{ .Values.muse_sd_ui_plugin.env.HPSA_TENANT }}"
        - name: HPSA_USER
          value: "{{ .Values.muse_sd_ui_plugin.env.HPSA_USER }}"
{{ include "MUSE.hpsa.password" (dict "all" . ) | indent 8 }}
        - name: LOG_LEVEL
          value: "{{ .Values.muse_sd_ui_plugin.env.LOG_LEVEL }}"
        - name: CALLBACK_ENDPOINT
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_sd_ui_plugin.name )) }}:{{ .Values.muse_sd_ui_plugin.port }}{{ .Values.muse_sd_ui_plugin.env.APP_PATH }}"
        - name: MUSE_ENABLED
          value: "y"
        - name: MUSE_NOTIFICATION_ENDPOINT
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_notif.name )) }}:{{ .Values.muse_notif.port }}{{ .Values.muse_notif.env.APP_PATH }}"
        - name: MUSE_JWT_SECRET
          value: "{{ default "secret_access" .Values.muse_container.env.MUSE_JWT_SECRET }}"
        - name: MUSE_CONFIGURATION_ENDPOINT
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_configuration.name )) }}:{{ .Values.muse_configuration.port }}{{ .Values.muse_configuration.env.APP_PATH }}"
        - name: ATTACHMENT_ENABLED
          value: "{{ .Values.muse_sd_ui_plugin.env.ATTACHMENT_ENABLED }}"
        {{- if and (eq .Values.muse_sd_ui_plugin.env.ATTACHMENT_ENABLED "y") (not .Values.secrets_as_volumes) (.Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_NAME) (.Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_KEY) }}
        - name: ATTACHMENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_NAME }}"
              key: "{{ .Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_KEY }}"
      {{- else }}
      {{- if or (.Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_NAME) (.Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_KEY) }}
      {{- fail ".Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_NAME and .Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_KEY parameters both have to be set or left empty!" }}
      {{- /*
      Use default Attachment Password }}
      */}}
      {{- end }}
        {{- end }}
{{ include "MUSE.env.redis"  (dict "all" . ) | indent 8 }}
{{ include "MUSE-helm-chart.spec.containers.certs" . | indent 6 }}
{{ include "MUSE-helm-chart.spec.containers.muse_fluentd.volumes" . | indent 6 }}
{{ include "MUSE.volume.secrets"  (dict "all" . ) | indent 6 }}
      {{- if and (.Values.secrets_as_volumes) (.Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_NAME) (.Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_KEY) }}
      - secret:
          name: "{{ .Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_NAME }}"
          items:
            - key: "{{ .Values.muse_sd_ui_plugin.env.ATTACHMENT_PASSWORD_SECRET_KEY }}"
              path: "ATTACHMENT_PASSWORD"
      {{- end }}
      {{- if and (.Values.secrets_as_volumes) (.Values.muse_sd_ui_plugin.env.HPSA_PASSWORD_SECRET_NAME) (.Values.muse_sd_ui_plugin.env.HPSA_PASSWORD_SECRET_KEY) }}
      - secret:
          name: "{{ .Values.muse_sd_ui_plugin.env.HPSA_PASSWORD_SECRET_NAME }}"
          items:
            - key: "{{ .Values.muse_sd_ui_plugin.env.HPSA_PASSWORD_SECRET_KEY }}"
              path: HPSA_PASSWORD
      {{- else }}
      {{- if or (.Values.muse_sd_ui_plugin.env.HPSA_PASSWORD_SECRET_NAME) (.Values.muse_sd_ui_plugin.env.HPSA_PASSWORD_SECRET_KEY) }}
      {{- fail ".Values.muse_sd_ui_plugin.env.HPSA_PASSWORD_SECRET_NAME and .Values.muse_sd_ui_plugin.env.HPSA_PASSWORD_SECRET_KEY parameters both have to be set or left empty!" }}
      {{- /*
      Use default HPSA Password }}
      */}}
      {{- end }}
      {{- end }}
{{- end }}