{{- if and .Values.muse.enabled .Values.muse_sd_ui.enabled }}
{{ include "MUSE.serviceAndDeployment"  (dict "all" . "muse_container" .Values.muse_sd_ui ) }}
{{ include "MUSE-helm-chart.template.containers.muse_sd_ui.volumeMounts" . | indent 8 }}
{{ include "MUSE.secrets.volumeMounts" (dict "all" . ) | indent 8 }}
        env:
        - name: HPESD_PATH
          value: /muse-sdui            
        - name: MUSE_AUTH_PROTOCOL
          value: "{{ .Values.muse_container.env.SERVICES_PROTOCOL }}"
        - name: MUSE_AUTH_HOST
          value: "{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_auth.name )) }}"
        - name: MUSE_AUTH_PORT
          value: "{{ .Values.muse_auth.port }}"
        - name: MUSE_REGISTRY_PROTOCOL
          value: "{{ .Values.muse_container.env.SERVICES_PROTOCOL }}"
        - name: MUSE_REGISTRY_HOST
          value: "{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_registry.name )) }}"
        - name: MUSE_REGISTRY_PORT
          value: "{{ .Values.muse_registry.port }}"
        - name: MUSE_CONFIG_PROTOCOL
          value: "{{ .Values.muse_container.env.SERVICES_PROTOCOL }}"
        - name: MUSE_CONFIG_HOST
          value: "{{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_configuration.name )) }}"
        - name: MUSE_CONFIG_PORT
          value: "{{ .Values.muse_configuration.port }}"
        - name: USER_NAME
          value: "{{ .Values.muse_sd_ui.env.USER_NAME }}"
{{- if not (.Values.secrets_as_volumes) }}
{{- if and (.Values.muse_sd_ui.env.PASSWORD_SECRET_NAME) (.Values.muse_sd_ui.env.PASSWORD_SECRET_KEY) }}
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.muse_sd_ui.env.PASSWORD_SECRET_NAME }}"
              key: "{{ .Values.muse_sd_ui.env.PASSWORD_SECRET_KEY }}"
{{- else }}
{{- if or (.Values.muse_sd_ui.env.PASSWORD_SECRET_NAME) (.Values.muse_sd_ui.env.PASSWORD_SECRET_KEY) }}
{{- fail "muse_sd_ui.env.PASSWORD_SECRET_NAME and muse_sd_ui.env.PASSWORD_SECRET_KEY parameters both have to be set or left empty!" }}
{{- /*
Use default MUSE Config Password }}
*/}}
{{- end }}
{{- end }}
{{- end }}
{{- if and (.Values.muse_sd_ui.env.PASSWORD_SECRET_NAME) (.Values.muse_sd_ui.env.PASSWORD_SECRET_KEY) }}
{{ include "MUSE.env.secrets" (dict "all" . "name" ".Values.muse_sd_ui.env.PASSWORD_SECRET_NAME" "key" ".Values.muse_sd_ui.env.PASSWORD_SECRET_KEY") | indent 8 }}
{{- end }}
        - name: CONFIGURE_USERS
          value: "{{ .Values.muse_sd_ui.env.CONFIGURE_USERS }}"
        - name: UI_PLUGIN_PROTOCOL
          value: "{{ .Values.muse_container.env.SERVICES_PROTOCOL }}"
        {{- if .Values.muse_container.master_node_ip }}
        - name: UI_PLUGIN_HOST
          value: "{{ .Values.muse_container.master_node_ip }}"
        {{- else }}
        - name: UI_PLUGIN_HOST
          value: "{{ .Values.muse_sd_ui.env.UI_PLUGIN_HOST }}"
        {{- end }}
        {{- if .Values.muse_sd_ui_plugin.nodePort }}
        - name: UI_PLUGIN_PORT
          value: "{{ .Values.muse_sd_ui_plugin.nodePort }}"
        {{- else }}
        - name: UI_PLUGIN_PORT
          value: "{{ .Values.muse_sd_ui.env.UI_PLUGIN_PORT }}"
        {{- end }}
        - name: HPESD_PORT
        {{- if .Values.install_assurance }}
          value: "{{ .Values.service_sdcl.port }}"
        {{- else }}
          value: "{{ .Values.service_sdsp.port }}"
        {{- end }}
        - name: HPESD_EXPOSED_PROTOCOL
          value: "{{ .Values.muse_container.env.SERVICES_PROTOCOL }}"
        {{- if .Values.muse_container.master_node_ip }}
        - name: HPESD_EXPOSED_HOST
          value: "{{ .Values.muse_container.master_node_ip }}"
        {{- else }}
        - name: HPESD_EXPOSED_HOST
          value: "{{ .Values.muse_sd_ui.env.HPESD_EXPOSED_HOST }}"
        {{- end }}
        {{- if .Values.muse_sd_ui.nodePort }}
        - name: HPESD_EXPOSED_PORT
          value: "{{ .Values.muse_sd_ui.nodePort }}"
        {{- else }}
        - name: HPESD_EXPOSED_PORT
          value: "{{ .Values.muse_sd_ui.env.HPESD_EXPOSED_PORT }}"
        {{- end }}
        - name: HPESD_INSTALL_ASSURANCE
        {{- if .Values.install_assurance }}
          value: "y"
        {{- else }}
        - name: HPESD_INSTALL_ASSURANCE
          value: "n"
        {{- end }}
{{ include "MUSE-helm-chart.spec.containers.muse_sd_ui.volumes" . | indent 6 }}
{{ include "MUSE-helm-chart.spec.containers.muse_fluentd.volumes" . | indent 6 }}
{{ include "MUSE.volume.secrets"  (dict "all" . ) | indent 6 }}
      {{- if and (.Values.secrets_as_volumes) (.Values.muse_sd_ui.env.PASSWORD_SECRET_NAME) (.Values.muse_sd_ui.env.PASSWORD_SECRET_KEY) }}
      - secret:
          name: "{{ .Values.muse_sd_ui.env.PASSWORD_SECRET_NAME }}"
          items:
            - key: "{{ .Values.muse_sd_ui.env.PASSWORD_SECRET_KEY }}"
              path: "PASSWORD"
      {{- end }}
{{- end }}