{{- if and .Values.muse.enabled .Values.muse_auth.enabled }}
{{ include "MUSE.serviceAndDeployment"  (dict "all" . "muse_container" .Values.muse_auth ) }}
{{ include "MUSE-helm-chart.template.containers.volumeMountsLog" . | indent 8 }}
{{- if or ( and .Values.muse_auth.env.AUTH_CALLBACK_SOURCE_CONFIG_MAP ( not .Values.muse_auth.env.AUTH_CALLBACK_SOURCE ) ) ( and ( not .Values.muse_auth.env.AUTH_CALLBACK_SOURCE_CONFIG_MAP ) .Values.muse_auth.env.AUTH_CALLBACK_SOURCE ) }}
{{- fail "Both muse_auth.env.AUTH_CALLBACK_SOURCE_CONFIG_MAP and muse_auth.env.AUTH_CALLBACK_SOURCE shall be defined - or both shall be left empty!" -}}}
{{- end }}
{{- if or ( and .Values.muse_auth.env.AUTH_CALLBACK_SOURCE_CONFIG_MAP .Values.muse_auth.env.AUTH_CALLBACK_SOURCE ) ( and ( not .Values.muse_auth.env.AUTH_CALLBACK_SOURCE_CONFIG_MAP ) .Values.muse_om_ui.enabled ) }}
        - name: auth-callback-src
          mountPath: /usr/src/app/src/external/
          readOnly: true
{{- end }}
{{ include "MUSE.secrets.volumeMounts" (dict "all" . ) | indent 8 }}
        env:
        {{- if .Values.muse_auth.env.APP_PATH }}
        - name: APP_PATH
          value: "{{ .Values.muse_auth.env.APP_PATH }}"
        {{- end }}
        - name: APP_PROTOCOL
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}"
        {{- if .Values.muse_auth.env.APP_CERTIFICATE }}
        - name: APP_CERTIFICATE
          value: "{{ .Values.muse_auth.env.APP_CERTIFICATE }}"
        {{- end }}
        {{- if .Values.muse_auth.env.APP_PRIVATE_KEY }}
        - name: APP_PRIVATE_KEY
          value: "{{ .Values.muse_auth.env.APP_PRIVATE_KEY }}"
        {{- end }}
        {{- if .Values.muse_auth.env.APP_SECURE_PROTOCOL }}
        - name: APP_SECURE_PROTOCOL
          value: "{{ .Values.muse_auth.env.APP_SECURE_PROTOCOL }}"
        {{- end }}
        {{- if .Values.muse_auth.env.APP_CORS_LIST }}
        - name: APP_CORS_LIST
          value: "{{ .Values.muse_auth.env.APP_CORS_LIST }}"
        {{- end }}
        {{- if .Values.muse_auth.env.APP_CONFIG_USER }}
        - name: APP_CONFIG_USER
          value: "{{ .Values.muse_auth.env.APP_CONFIG_USER }}"
        {{- end }}
        {{- if .Values.muse_auth.env.APP_CONFIG_PASS }}
        - name: APP_CONFIG_PASS
          value: "{{ .Values.muse_auth.env.APP_CONFIG_PASS }}"
        {{- end }}
        {{- if .Values.muse_auth.env.APP_BODY_LIMIT }}
        - name: APP_BODY_LIMIT
          value: "{{ .Values.muse_auth.env.APP_BODY_LIMIT }}"
        {{- end }}
        {{- if .Values.muse_auth.env.PAGE_LIMIT_DEFAULT }}
        - name: PAGE_LIMIT_DEFAULT
          value: "{{ .Values.muse_auth.env.PAGE_LIMIT_DEFAULT }}"
        {{- end }}
        {{- if .Values.muse_auth.env.AUTH_CALLBACK_SOURCE }}
        - name: AUTH_CALLBACK_SOURCE
          value: {{ .Values.muse_auth.env.AUTH_CALLBACK_SOURCE }}
        {{- else }}
           {{- if and ( not .Values.muse_auth.env.AUTH_CALLBACK_SOURCE ) .Values.muse_om_ui.enabled }}
        - name: AUTH_CALLBACK_SOURCE
          value: post-authentication-{{ .Values.muse_auth.env.AUTH_TYPE }}
          {{- end }}
        {{- end }}
        - name: AUTH_TYPE
          value: "{{ .Values.muse_auth.env.AUTH_TYPE }}"
        {{- if .Values.muse_auth.env.AUTH_USERNAME_FIELDS }}
        - name: AUTH_USERNAME_FIELDS
          value: "{{ .Values.muse_auth.env.AUTH_USERNAME_FIELDS }}"
        {{- end }}
        {{- if .Values.muse_auth.env.AUTH_ROLES_FIELDS }}
        - name: AUTH_ROLES_FIELDS
          value: "{{ .Values.muse_auth.env.AUTH_ROLES_FIELDS }}"
        {{- end }}
        {{- if .Values.muse_auth.env.AUTH_PERMISSIONS_FIELDS }}
        - name: AUTH_PERMISSIONS_FIELDS
          value: "{{ .Values.muse_auth.env.AUTH_PERMISSIONS_FIELDS }}"
        {{- end }}
        {{- if .Values.muse_auth.env.LOG_FILE }}
        - name: LOG_FILE
          value: "{{ .Values.muse_auth.env.LOG_FILE }}"
        {{- end }}
        {{- if .Values.muse_auth.env.LOG_FILE_SIZE }}
        - name: LOG_FILE_SIZE
          value: "{{ .Values.muse_auth.env.LOG_FILE_SIZE }}"
        {{- end }}
        {{- if .Values.muse_auth.env.LOG_FILE_BACKUPS }}
        - name: LOG_FILE_BACKUPS
          value: "{{ .Values.muse_auth.env.LOG_FILE_BACKUPS }}"
        {{- end }}
        {{- if .Values.muse_auth.env.LOG_LEVEL }}
        - name: LOG_LEVEL
          value: "{{ .Values.muse_auth.env.LOG_LEVEL }}"
        {{- end }}
        {{- if .Values.muse_auth.env.LOG_PATTERN }}
        - name: LOG_PATTERN
          value: "{{ .Values.muse_auth.env.LOG_PATTERN }}"
        {{- end }}
{{ include "MUSE.env.db" (dict "all" . ) | indent 8 }}
        {{- if .Values.muse_container.env.JWT_SECRET_ACCESS }}
        - name: JWT_SECRET_ACCESS
          value: "{{ .Values.muse_container.env.JWT_SECRET_ACCESS }}"
        {{- end }}
        {{- if .Values.muse_auth.env.JWT_SECRET_REFRESH }}
        - name: JWT_SECRET_REFRESH
          value: "{{ .Values.muse_auth.env.JWT_SECRET_REFRESH }}"
        {{- end }}
        {{- if .Values.muse_auth.env.JWT_TIMEOUT_ACCESS }}
        - name: JWT_TIMEOUT_ACCESS
          value: "{{ .Values.muse_auth.env.JWT_TIMEOUT_ACCESS }}"
        {{- end }}
        {{- if .Values.muse_auth.env.JWT_TIMEOUT_REFRESH }}
        - name: JWT_TIMEOUT_REFRESH
          value: "{{ .Values.muse_auth.env.JWT_TIMEOUT_REFRESH }}"
        {{- end }}
        {{ if not .Values.muse_gateway.enabled }}
        {{- if .Values.muse_container.master_node_ip }}
        - name: SHELL_LOGIN_CALLBACK
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.muse_container.master_node_ip }}/auth/callback"
        - name: SHELL_LOGOUT_CALLBACK
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.muse_container.master_node_ip }}"
        {{- else }}
        {{- if .Values.ingress.enabled }}
        - name: SHELL_LOGIN_CALLBACK
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.ingress.host }}/auth/callback"
        - name: SHELL_LOGOUT_CALLBACK
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.ingress.host }}"
        {{- else }}
        - name: SHELL_LOGIN_CALLBACK
          value: "{{ .Values.muse_auth.env.SHELL_LOGIN_CALLBACK }}"
        - name: SHELL_LOGOUT_CALLBACK
          value: "{{ .Values.muse_auth.env.SHELL_LOGOUT_CALLBACK }}"
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.muse_auth.env.PRIMARY_TIMEOUT }}
        - name: PRIMARY_TIMEOUT
          value: "{{ .Values.muse_auth.env.PRIMARY_TIMEOUT }}"
        {{- end }}
{{ include "MUSE.env.redis"  (dict "all" . ) | indent 8 }}
        {{- if eq .Values.muse_auth.env.AUTH_TYPE "local" }}
          # EMPTY?
        {{- end }} # end AUTH_TYPE local check
        {{- if eq .Values.muse_auth.env.AUTH_TYPE "saml" }}
        - name: SAML_ISSUER
          value: "{{ .Values.muse_auth.env.SAML_ISSUER }}"
        - name: SAML_CLIENT
          value: "{{ .Values.muse_auth.env.SAML_CLIENT }}"
        - name: SAML_AUDIENCE
          value: "{{ .Values.muse_auth.env.SAML_AUDIENCE }}"
        - name: SAML_CERT
          value: "{{ .Values.muse_auth.env.SAML_CERT }}"
        - name: SAML_SIGNATURE_ALGORITHM
          value: "{{ .Values.muse_auth.env.SAML_SIGNATURE_ALGORITHM }}"
        - name: SAML_DIGEST_ALGORITHM
          value: "{{ .Values.muse_auth.env.SAML_DIGEST_ALGORITHM }}"
        - name: SAML_IDENTIFIER_FORMAT
          value: "{{ .Values.muse_auth.env.SAML_IDENTIFIER_FORMAT }}"
        - name: SAML_WANT_ASSERTIONS_SIGNED
          value: "{{ .Values.muse_auth.env.SAML_WANT_ASSERTIONS_SIGNED }}"
        - name: SAML_ACCEPTED_CLOCK_SKEW_MS
          value: "{{ .Values.muse_auth.env.SAML_ACCEPTED_CLOCK_SKEW_MS }}"
        - name: SAML_MAX_ASSERTION_AGE_MS
          value: "{{ .Values.muse_auth.env.SAML_MAX_ASSERTION_AGE_MS }}"
        - name: SAML_ATTRIBUTE_CONSUMING_SERVICE_INDEX
          value: "{{ .Values.muse_auth.env.SAML_ATTRIBUTE_CONSUMING_SERVICE_INDEX }}"
        - name: SAML_DISABLE_REQUESTED_AUTHN_CONTEXT
          value: "{{ .Values.muse_auth.env.SAML_DISABLE_REQUESTED_AUTHN_CONTEXT }}"
        - name: SAML_AUTHN_CONTEXT
          value: "{{ .Values.muse_auth.env.SAML_AUTHN_CONTEXT }}"
        - name: SAML_RAC_COMPARISON
          value: "{{ .Values.muse_auth.env.SAML_RAC_COMPARISON }}"
        - name: SAML_FORCE_CONTEXT
          value: "{{ .Values.muse_auth.env.SAML_FORCE_CONTEXT }}"
        - name: SAML_PASSIVE
          value: "{{ .Values.muse_auth.env.SAML_PASSIVE }}"
        - name: SAML_PROVIDER_NAME
          value: "{{ .Values.muse_auth.env.SAML_PROVIDER_NAME }}"
        - name: SAML_SKIP_REQUEST_COMPRESSION
          value: "{{ .Values.muse_auth.env.SAML_SKIP_REQUEST_COMPRESSION }}"
        - name: SAML_AUTHN_REQUEST_BINDING
          value: "{{ .Values.muse_auth.env.SAML_AUTHN_REQUEST_BINDING }}"
        - name: SAML_DISABLE_REQUEST_ACS_URL
          value: "{{ .Values.muse_auth.env.SAML_DISABLE_REQUEST_ACS_URL }}"
        - name: SAML_VALIDATE_IN_RESPONSE_TO
          value: "{{ .Values.muse_auth.env.SAML_VALIDATE_IN_RESPONSE_TO }}"
        - name: SAML_REQUEST_ID_EXPIRATION_PERIOD_MS
          value: "{{ .Values.muse_auth.env.SAML_REQUEST_ID_EXPIRATION_PERIOD_MS }}"
        - name: SAML_IDP_ISSUER
          value: "{{ .Values.muse_auth.env.SAML_IDP_ISSUER }}"
        - name: SAML_PASS_REQ_TO_CALLBACK
          value: "{{ .Values.muse_auth.env.SAML_PASS_REQ_TO_CALLBACK }}"
        - name: SAML_NAME
          value: "{{ .Values.muse_auth.env.SAML_NAME }}"
        - name: SAML_LOGOUT_URL
          value: "{{ .Values.muse_auth.env.SAML_LOGOUT_URL }}"
        {{- if and (.Values.muse_container.master_node_ip) (.Values.muse_auth.nodePort) }}
        - name: SAML_LOGIN_ENTRY
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.muse_container.master_node_ip }}/saml/login"
        - name: SAML_LOGIN_CALLBACK
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.muse_container.master_node_ip }}/saml/login/callback"
        - name: SAML_LOGOUT_ENTRY
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.muse_container.master_node_ip }}/saml/logout"
        - name: SAML_LOGOUT_CALLBACK
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.muse_container.master_node_ip }}/saml/logout/callback"
        {{- else }}
        {{- if .Values.ingress.enabled }}
        - name: SAML_LOGIN_ENTRY
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.ingress.host }}/auth/callback"
        - name: SAML_LOGIN_CALLBACK
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.ingress.host }}/auth/callback"
        - name: SAML_LOGOUT_ENTRY
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.ingress.host }}/auth/callback"
        - name: SAML_LOGOUT_CALLBACK
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.ingress.host }}/auth/callback"
        {{- else }}
        - name: SAML_LOGIN_ENTRY
          value: "{{ .Values.muse_auth.env.SAML_LOGIN_ENTRY }}"
        - name: SAML_LOGIN_CALLBACK
          value: "{{ .Values.muse_auth.env.SAML_LOGIN_CALLBACK }}"
        - name: SAML_LOGOUT_ENTRY
          value: "{{ .Values.muse_auth.env.SAML_LOGOUT_ENTRY }}"
        - name: SAML_LOGOUT_CALLBACK
          value: "{{ .Values.muse_auth.env.SAML_LOGOUT_CALLBACK }}"
        {{- end }}
        {{- end }}
        {{- end }} # end AUTH_TYPE saml check
        {{- if eq .Values.muse_auth.env.AUTH_TYPE "oidc" }}
        {{- if and (.Values.muse_container.master_node_ip) (.Values.muse_auth.nodePort) }}  
        - name: OIDC_LOGIN_CALLBACK
          value: "{{ .Values.muse_auth.env.OIDC_LOGIN_CALLBACK }}"
        - name: OIDC_LOGOUT_CALLBACK
          value: "{{ .Values.muse_auth.env.OIDC_LOGOUT_CALLBACK }}"
        {{- else }}
        {{- if .Values.ingress.enabled }}
        - name: OIDC_LOGIN_CALLBACK
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.ingress.host }}/oidc/login/callback"
        - name: OIDC_LOGOUT_CALLBACK
          value: "{{ .Values.muse_container.env.APP_PROTOCOL }}://{{ .Values.ingress.host }}/oidc/logout/callback"
        {{- else }}
        - name: OIDC_LOGIN_CALLBACK
          value: "{{ .Values.muse_auth.env.OIDC_LOGIN_CALLBACK }}"
        - name: OIDC_LOGOUT_CALLBACK
          value: "{{ .Values.muse_auth.env.OIDC_LOGOUT_CALLBACK }}"
        {{- end }}
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_TYPE }}
        - name: OIDC_TYPE
          value: "{{ .Values.muse_auth.env.OIDC_TYPE }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_ISSUER }}
        - name: OIDC_ISSUER
          value: "{{ .Values.muse_auth.env.OIDC_ISSUER }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_AUTO_DISCOVER }}
        - name: OIDC_AUTO_DISCOVER
          value: "{{ .Values.muse_auth.env.OIDC_AUTO_DISCOVER }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_AUTHORIZATION_ENDPOINT }}
        - name: OIDC_AUTHORIZATION_ENDPOINT
          value: "{{ .Values.muse_auth.env.OIDC_AUTHORIZATION_ENDPOINT }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_USERNAME_TOKEN }}
        - name: OIDC_USERNAME_TOKEN
          value: "{{ .Values.muse_auth.env.OIDC_USERNAME_TOKEN }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_ROLES_TOKEN}}
        - name: OIDC_ROLES_TOKEN
          value: "{{ .Values.muse_auth.env.OIDC_ROLES_TOKEN }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_TOKEN_ENDPOINT }}
        - name: OIDC_TOKEN_ENDPOINT
          value: "{{ .Values.muse_auth.env.OIDC_TOKEN_ENDPOINT }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_USER_INFO_ENDPOINT }}
        - name: OIDC_USER_INFO_ENDPOINT
          value: "{{ .Values.muse_auth.env.OIDC_USER_INFO_ENDPOINT }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_END_SESSION_ENDPOINT }}
        - name: OIDC_END_SESSION_ENDPOINT
          value: "{{ .Values.muse_auth.env.OIDC_END_SESSION_ENDPOINT }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_JWKS_URI }}
        - name: OIDC_JWKS_URI
          value: "{{ .Values.muse_auth.env.OIDC_JWKS_URI }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_CLIENT }}
        - name: OIDC_CLIENT
          value: "{{ .Values.muse_auth.env.OIDC_CLIENT }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_SECRET }}
        - name: OIDC_SECRET
          value: "{{ .Values.muse_auth.env.OIDC_SECRET }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_TOKEN_ENDPOINT_AUTH_METHOD }}
        - name: OIDC_TOKEN_ENDPOINT_AUTH_METHOD
          value: "{{ .Values.muse_auth.env.OIDC_TOKEN_ENDPOINT_AUTH_METHOD }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_ID_TOKEN_SIGN_ALGORITHM }}
        - name: OIDC_ID_TOKEN_SIGN_ALGORITHM
          value: "{{ .Values.muse_auth.env.OIDC_ID_TOKEN_SIGN_ALGORITHM }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_USER_INFO_SIGN_ALGORITHM }}
        - name: OIDC_USER_INFO_SIGN_ALGORITHM
          value: "{{ .Values.muse_auth.env.OIDC_USER_INFO_SIGN_ALGORITHM }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_SCOPE }}
        - name: OIDC_SCOPE
          value: "{{ .Values.muse_auth.env.OIDC_SCOPE }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_USERNAME_FIELDS }}
        - name: OIDC_USERNAME_FIELDS
          value: "{{ .Values.muse_auth.env.OIDC_USERNAME_FIELDS }}"
        {{- end }}
        {{- if .Values.muse_auth.env.OIDC_ROLES_FIELDS }}
        - name: OIDC_ROLES_FIELDS
          value: "{{ .Values.muse_auth.env.OIDC_ROLES_FIELDS }}"
        {{- end }}
        {{- end }} # end AUTH_TYPE oidc check
{{- include "MUSE.headers" (dict "all" . "muse_container" .Values.muse_auth ) }}
{{ include "MUSE-helm-chart.spec.containers.log.volume" . | indent 6 }}
{{- if and .Values.muse_auth.env.AUTH_CALLBACK_SOURCE_CONFIG_MAP .Values.muse_auth.env.AUTH_CALLBACK_SOURCE }}
      - name: auth-callback-src
        configMap:
          name: {{ .Values.muse_auth.env.AUTH_CALLBACK_SOURCE_CONFIG_MAP }}
{{- end }}
{{- if and ( not .Values.muse_auth.env.AUTH_CALLBACK_SOURCE_CONFIG_MAP ) .Values.muse_om_ui.enabled }}
      - name: auth-callback-src
        configMap:
          name: auth-callback-source-config
{{- end }}
{{ include "MUSE-helm-chart.spec.containers.muse_fluentd.volumes" . | indent 6 }}
{{ include "MUSE.volume.secrets"  (dict "all" . ) | indent 6 }}
{{- end }}