{{- if and .Values.muse.enabled .Values.muse_notif.enabled }}
{{ include "MUSE.serviceAndDeployment"  (dict "all" . "muse_container" .Values.muse_notif ) }}
{{ include "MUSE-helm-chart.template.containers.volumeMountsLog" . | indent 8 }}
        env:
        - name: REDIS_ENABLED
          value: "{{ .Values.muse_notif.env.REDIS_ENABLED }}"
        - name: REDIS_HOST
          value: "{{ .Values.muse_notif.env.REDIS_HOST }}"
        - name: REDIS_PORT
          value: "{{ .Values.muse_notif.env.REDIS_PORT }}"
        - name: REDIS_PASSWORD
          value: "{{ .Values.muse_notif.env.REDIS_PASSWORD }}"
{{ include "MUSE-helm-chart.spec.containers.log.volume" . | indent 6 }}
{{- end }}