{{- if  (.Values.prometheus.enabled)  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: wf-config
  namespace: servicedirector
data:
  config.xml: |
    <?xml version="1.0" encoding="utf-8" ?>
    <!DOCTYPE Engine SYSTEM "solutionmwfm.dtd">
    <Engine>
      <Module>
        <Name>self_monitoring</Name>
        <Class-Name>com.hp.ov.activator.mwfm.engine.module.SelfMonitoringModule</Class-Name>
        <Param name="poll_interval" value="10000"/>
        <Param name="threshold_percent_heap_size" value="80"/>
        <Param name="threshold_percent_maxworklistlength" value="1"/>
        <Param name="send_snmp_trap" value="true"/>
        <Param name="snmp_module" value="snmp_sender"/>
        <Param name="log_alarm" value="true"/>
        <Param name="max_alarm_entries" value="3"/>
        <Param name="audit_events" value="true"/>
        <Param name="granularities" value="1,5,30,240,1440,10080"/>
        <Param name="samples" value="360"/>
      </Module>
    </Engine>




{{- end }}
---
{{- if  (.Values.prometheus.enabled)  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grok-config
  namespace: servicedirector
data:
  config.yml: |-
    global:
        config_version: 2
    input:
        type: file
        path: /alarms-log/alarms_active.xml
        readall: true # Read from the beginning of the file? False means we start at the end of the file and read only new lines.
    grok:
        patterns_dir: ./patterns
    metrics:
        - type: counter
          name: nodes_offline
          help: Total number of SA nodes offline.
          match: "The node : %{GREEDYDATA:node} has gone offline"
          labels:
              data_message: '{{.node}}'
        - type: counter
          name: workflows_threshold
          help: Total length of the current work list.
          match: "Current work list length: %{INT:length} has exceeded the set threshold :%{INT:threshold}"
          labels:
              data_length: '{{.length}}'
              data_threshold: '{{.threshold}}'
    server:
        port: 9144

{{- end }}