
# SA StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulset_sa.name}}
  labels:
    app: {{.Values.statefulset_sa.app}}
    app.kubernetes.io/component: sa
  namespace: {{.Release.Namespace}} 
spec:
  replicas: {{ .Values.statefulset_sa.replicaCount }}
  serviceName: {{ .Values.service_sa.name }}
  selector:
    matchLabels:
      app: {{.Values.statefulset_sa.app}}
  template:
    metadata:
      labels:
        app: {{.Values.statefulset_sa.app}}     
        {{- range $key, $val := .Values.sa.podLabels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{- include "getServiceAccountName" . | indent 1 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.sa.securityContext.runAsUser }}
      {{- end }}

      affinity: {{- include "templateValue" ( dict "value" .Values.sa.affinity "context" $ ) | nindent 8 }}
      topologySpreadConstraints: {{- include "templateValue" ( dict "value" .Values.sa.topologySpreadConstraints "context" $ ) | nindent 8 }}
      containers:
      {{/* *************** SA Container ********************* */}}
      - name: {{.Values.sa.image.name}}
        image: "{{.Values.sa.image.registry}}{{.Values.sa.image.name}}:{{.Values.sa.image.tag}}"
        imagePullPolicy: {{ default "Always" .Values.sa.image.pullPolicy }}
        ports:
{{ include "addPort" .Values.sa.ports.gui | indent 8 }}
{{ include "addSAHealthCheck" .Values.sa | indent 8 }}
{{ include "addResources" .Values.sa | indent 8 }}
        {{- if (.Values.sa.licenseEnabled) }}
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - cp /mnt/license /license
        {{- end }}
        volumeMounts:
        {{- if   ( .Values.secrets_as_volumes )  }}  
        - name: secrets
          mountPath: "/secrets"  
        {{- end }}  
        {{- if (.Values.sa.licenseEnabled) }}
        - name: sa-license
          mountPath: "/mnt"
          readOnly: true
        {{- end }}
        {{- if (eq (include "isMountSALogsEnabled" .) "true") }}
        - name: jboss-log
          mountPath: /opt/HP/jboss/standalone/log/
        - name: sa-log
          mountPath: /var/opt/OV/ServiceActivator/log/
        {{- end }}
        {{- if (.Values.sa.sshEnabled) }}
        - name: ssh-identity
          mountPath: "/ssh"
          readOnly: true
        {{- end }}
        {{- if .Values.sa.env_configmap_name }}
        envFrom:
        - configMapRef:
            name: {{ .Values.sa.env_configmap_name }}
        {{- end }}
        env:
        - name: SACONF_activator_db_vendor
          value: "{{ .Values.sa.env.db_vendor }}"
        - name: SACONF_activator_db_hostname
          value: "{{- tpl .Values.sa.env.db_hostname $ }}"
        {{- if (.Values.sa.env.db_port) }}
        - name: SACONF_activator_db_port
          value: "{{ .Values.sa.env.db_port }}"
        {{- end }}
        - name: SACONF_activator_db_instance
          value: "{{ .Values.sa.env.db_instance }}"
        - name: SACONF_activator_db_user
          value: "{{ .Values.sa.env.db_user }}"
        {{- if  not  (.Values.secrets_as_volumes )  }}   
        - name: SACONF_activator_db_password
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.sa.env.db_password_key }}"
              name: "{{ .Values.sa.env.db_password_name }}"
        {{- end }}

        {{- /* Activator Config variables */ -}}    
        
        {{- if (.Values.sa.env.rolling_upgrade ) }}
        - name: SACONF_activator_rolling_upgrade
          value: "{{ .Values.sa.env.rolling_upgrade }}"
        {{- end }}
        {{- if (.Values.sa.env.activator_conf_jvm_max_memory ) }}
        - name: SACONF_activator_conf_jvm_max_memory
          value: "{{ .Values.sa.env.activator_conf_jvm_max_memory }}"
        {{- end }}
        {{- if (.Values.sa.env.activator_conf_jvm_min_memory ) }}
        - name: SACONF_activator_conf_jvm_min_memory
          value: "{{ .Values.sa.env.activator_conf_jvm_min_memory }}"
        {{- end }}
        {{- if (.Values.sa.sshEnabled) }}
        - name: SACONF_activator_conf_ssh_identity
          value: /ssh/identity
        {{- end }}
      {{- if (eq (include "isProxyMetricsEnabled" .) "true") }}

      {{- /* *************** Envoy Container ********************* */}}

      - name: envoy
        image: "{{.Values.envoy.image.registry}}{{.Values.envoy.image.name}}:{{.Values.envoy.image.tag}}"
        imagePullPolicy: {{ default "Always" .Values.envoy.image.pullPolicy }}
        ports:
        - containerPort: 9991
          name: envoy-port
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/bitnami/envoy/conf/envoy.yaml
          name: envoy-config-metrics
          readOnly: true
          subPath: envoy.yaml
      {{- end }}

      {{- if (eq (include "isMountSALogsEnabled" .) "true") -}}

      {{-   $logsSource := "fluentd" -}}
      {{-   if .Values.sa.serveLogs.source -}}{{- if .Values.sa.serveLogs.source.type -}}
        {{-   $logsSource = .Values.sa.serveLogs.source.type }}
      {{-   end -}}{{- end -}}

      {{-   if and (eq $logsSource "fluentd") -}}

      {{- /* *************** Fluentd Container ********************* */}}

      - name: fluentd
        image: "{{.Values.fluentd.image.registry}}{{.Values.fluentd.image.name}}:{{.Values.fluentd.image.tag}}"
        imagePullPolicy: {{ default "Always" .Values.fluentd.image.pullPolicy }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: FLUENTD_CONF
          value: fluentd.conf
        - name: FLUENTD_OPT
        ports:
        - containerPort: 24224
          name: tcp
          protocol: TCP
        - containerPort: 9880
          name: http
          protocol: TCP
        - containerPort: 24231
          name: metrics
        resources:
          requests:
            memory: {{ .Values.fluentd.memoryrequested }}
            cpu: {{ .Values.fluentd.cpurequested }}
          limits:
            {{- if (.Values.fluentd.memorylimit) }}
            memory: {{ .Values.fluentd.memorylimit }}
            {{- end }}
            {{- if (.Values.fluentd.cpulimit) }}
            cpu: {{ .Values.fluentd.cpulimit }}
            {{- end }}
        volumeMounts:
        - mountPath: /opt/bitnami/fluentd/conf/
          name: fluentd-config
        - mountPath: /opt/bitnami/fluentd/logs/buffers
          name: buffer
        - name: jboss-log
          mountPath: /jboss-log
        - name: sa-log
          mountPath: /sa-log
          subPathExpr: $(POD_NAME)
      {{-   end -}}
      {{- end -}}

      {{- /* *************** End of Containers section ********************* */}}

      volumes:
      {{- if   (.Values.secrets_as_volumes )  }}  
      - name: secrets
        secret:
          secretName: {{ .Values.sa.env.db_password_name }}
          items:
          - key: {{ .Values.sa.env.db_password_key }}
            path: activator_db_password
      {{- end }}
      {{- if (.Values.sa.licenseEnabled) }}
      - name: sa-license
        secret:
          secretName: sa-license-secret
      {{- end }}
      {{- if (.Values.sa.sshEnabled) }}
      - name: ssh-identity
        secret:
          secretName: ssh-identity
          defaultMode: 0600
      {{- end }}
      {{- if (eq (include "isProxyMetricsEnabled" .) "true") }}
      - name: envoy-config-metrics
        configMap:
          defaultMode: 420
          name: envoy-metrics
      {{- end }}
      {{- if (eq (include "isMountSALogsEnabled" .) "true") }}
      - name: jboss-log
        emptyDir: {}
      - name: sa-log
        emptyDir: {}
      - name: fluentd-config
        configMap:
          defaultMode: 420
          name: fluentd-config
      - name: buffer
        emptyDir: {}
      {{- end }}
