{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "getServiceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "getChartName" . }}
    chart: {{ template "getChartLabel" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.serviceAccount.imagePullSecrets }}
{{- end }}
{{- end }}
