apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sd-sp
  labels:
    app: sd-sp
  namespace: servicedirector
spec:
  replicas: 2
  serviceName: sd-sp
  selector:
    matchLabels:
      app: sd-sp
  template:
    metadata:
      labels:
        app: sd-sp
    spec:
      containers:
        - image: hub.docker.hpecorp.net/cms-sd/sd-sp
          imagePullPolicy: Always
          name: sd-sp
          env:
            - name: SDCONF_activator_db_vendor
              value: PostgreSQL
            - name: SDCONF_activator_db_hostname
              value: postgres-nodeport
            - name: SDCONF_activator_db_instance
              value: sa
            - name: SDCONF_activator_db_user
              value: sa
            - name: SDCONF_activator_db_password
              value: secret
          ports:
            - containerPort: 8080
              name: 8080tcp01
          livenessProbe:
            exec:
              command:
                - /docker/healthcheck.sh
            initialDelaySeconds: 360
            periodSeconds: 15
          readinessProbe:
            exec:
              command:
                - /docker/healthcheck.sh
            initialDelaySeconds: 180
            periodSeconds: 15

---

apiVersion: v1
kind: Service
metadata:
  name: sd-sp-nodeport
  namespace: servicedirector
spec:
  ports:
    - name: 8080tcp01
      nodePort: 32514
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sd-sp
  sessionAffinity: ClientIP
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-ui
  labels:
    app: sd-ui
  namespace: servicedirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-ui
  template:
    metadata:
      labels:
        app: sd-ui
    spec:
      containers:
        - image: hub.docker.hpecorp.net/cms-sd/sd-ui
          imagePullPolicy: Always
          name: sd-ui
          env:
            - name: SDCONF_sdui_async_host
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SDCONF_sdui_provision_host
              value: sd-sp-nodeport
            - name: SDCONF_uoc_couchdb_host
              value: sduicouchdb-couchdb
            - name: SDCONF_uoc_couchdb_admin_username
              value: admin
            - name: SDCONF_uoc_couchdb_admin_password
              value: admin
          ports:
            - containerPort: 3000
              name: 3000tcp01
          livenessProbe:
            exec:
              command:
                - /docker/healthcheck.sh
            initialDelaySeconds: 200
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /docker/healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: sd-ui-nodeport
  namespace: servicedirector
spec:
  ports:
    - name: 3000tcp01
      nodePort: 32516
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: sd-ui
  sessionAffinity: ClientIP
  type: NodePort
