{{- if  and (eq (include "elk.enabled" .) "true")  (.Values.elk.elastic.enabled)  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: {{ template "monitoring.namespace" . }}
  labels:
    app: elasticsearch
spec:
  serviceName: "elasticsearch-service-headless"
  replicas: {{ .Values.elk.elastic.replicas }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        {{- range $key, $val := .Values.elk.podLabels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    spec:
    {{- if .Values.elk.elastic.runAsUser }}
      securityContext:
        runAsUser: {{ .Values.elk.elastic.runAsUser }}
    {{- end }}
      affinity: {{- include "sd.templateValue" ( dict "value" .Values.elk.elastic.affinity "context" $ ) | nindent 8 }}    
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:{{.Values.elk.version}}
        imagePullPolicy: {{ include "resolve.imagePullPolicy" (dict "top" . "specificPullPolicy" .Values.elk.pullPolicy) }}
        name: elasticsearch
        startupProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          failureThreshold: 10
          periodSeconds: 20
        livenessProbe:
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
        resources:
          requests:
            memory: {{.Values.elk.elastic.memoryrequested}}
            cpu: {{.Values.elk.elastic.cpurequested}}
          limits:
{{- if (.Values.elk.elastic.memorylimit ) }}                 
            memory: {{ .Values.elk.elastic.memorylimit }}
{{- end }}                  
{{- if (.Values.elk.elastic.cpulimit ) }} 
            cpu: {{ .Values.elk.elastic.cpulimit }} 
{{- end }}           
        ports:
        - containerPort: 9200
          name: restapi
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
{{- if .Values.elk.elastic.persistence }}
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
{{- end }}       
        - name: elasticsearch-logging
          mountPath: /data
        {{- if .Values.elk.elastic.extraVolumeMounts }}
        {{- toYaml .Values.elk.elastic.extraVolumeMounts | nindent 8 }}
        {{- end }}
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if (.Values.elk.elastic.masterService ) }} 
        - name: "node.name"
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name           
        - name: "cluster.name"
          value: "elasticsearch-cluster"     
        - name: cluster.initial_master_nodes
          value: "{{ template "elasticsearch.endpoints" . }}"
        - name: discovery.zen.ping.unicast.hosts
          value: "elasticsearch-service-headless"
        - name: network.host
          value: "{{ .Values.elk.elastic.networkHost }}"   
        - name: ES_JAVA_OPTS
          value: "{{ .Values.elk.elastic.esJavaOpts }}"          
{{- else }}
        - name: "discovery.type"
          value: "single-node" 
{{- end }}     
      {{- if .Values.elk.elastic.extraInitContainers }}
      initContainers:
      {{- toYaml .Values.elk.elastic.extraInitContainers | nindent 6 }}
      {{- end }}
      volumes:
      - name: elasticsearch-logging
        emptyDir: {}
      {{- if .Values.elk.elastic.extraVolumes }}
      {{- toYaml .Values.elk.elastic.extraVolumes | nindent 6 }}
      {{- end }}
{{- if not .Values.elk.elastic.persistence }}
      - name: "elasticsearch-data"
        emptyDir: {}
{{- else }}         
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        labels:
          app: elasticsearch
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elk.elastic.persistentSize | quote }}
        storageClassName: {{ template "sd-helm-chart.elastic.storageclass" . }}
{{- end }} 
{{- end }} 
---
{{- if  and (eq (include "elk.enabled" .) "true")  (.Values.elk.elastic.enabled)  }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: {{ template "monitoring.namespace" . }}
  labels:
    app: elasticsearch-service
    {{- range $key, $val := .Values.service_elk.podLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}   
spec:
  type: {{ .Values.elk.elastic.servicetype | quote }}
  {{- if and (eq .Values.elk.elastic.servicetype "LoadBalancer") (not (empty .Values.elk.elastic.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.elk.elastic.loadBalancerIP }}
  {{- end }}
  ports:
  - port: 9200
    protocol: TCP
    targetPort: restapi
    {{- if and (or (eq .Values.elk.elastic.servicetype "NodePort") (eq .Values.elk.elastic.servicetype "LoadBalancer")) (not (empty .Values.elk.elastic.nodePort)) }}
    nodePort: {{ .Values.elk.elastic.nodePort }}
    {{- end }}
  selector:
    app: elasticsearch
{{- end }}

---

{{- if  and (eq (include "elk.enabled" .) "true")  (.Values.elk.elastic.enabled)  }}
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-service-headless
  namespace: {{ template "monitoring.namespace" . }}
  labels:
    app: elasticsearch-headless-service
    {{- range $key, $val := .Values.service_elk.podLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}   
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None 
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    app: elasticsearch
  ports:
  - name: "http"
    port: 9200
  - name: "transport" 
    port: 9300

{{- end }}
