apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-ui
  labels:
    app: sd-ui
  namespace: servicedirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-ui
  template:
    metadata:
      labels:
        app: sd-ui
    spec:
      containers:
      - image: hub.docker.hpecorp.net/cms-sd/sd-ui
        imagePullPolicy: IfNotPresent
        name: sd-ui
        env:
        - name: SDCONF_sdui_install_assurance
          value: "yes"
        - name: SDCONF_sdui_provision_host
          value: sd-sp-nodeport
        - name: SDCONF_sdui_async_host
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SDCONF_uoc_couchdb_host
          value: sduicouchdb-couchdb
        - name: SDCONF_uoc_couchdb_admin_username
          value: admin
        - name: SDCONF_uoc_couchdb_admin_password
          value: admin
        ports:
        - containerPort: 3000
          name: 3000tcp01
        livenessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: 200
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: 30
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: sd-ui-nodeport
  namespace: servicedirector
spec:
  ports:
  - name: 3000tcp01
    nodePort: 32515
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sd-ui
  sessionAffinity: ClientIP
  type: NodePort
