{{- if  (.Values.prometheus.enabled)  }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{.Values.monitoringNamespace}}
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30033
  selector:
    app: grafana
  type: NodePort
{{- end }}