{{/*
Generate the full grafana image url
*/}}
{{- define "grafana.fullpath" -}}
{{- if .Values.prometheus.grafana.image -}}
  {{- if .Values.prometheus.grafana.image.registry -}}
    {{- printf "%s" .Values.prometheus.grafana.image.registry -}}
  {{- end -}}
  {{- if .Values.prometheus.grafana.image.name -}}
    {{- printf "%s" .Values.prometheus.grafana.image.name -}}
  {{- end -}}
  {{- if .Values.prometheus.grafana.image.tag -}}
    {{- printf ":%s" .Values.prometheus.grafana.image.tag -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- if  and  (eq (include "prometheus.enabled" .) "true")  (.Values.prometheus.server_enabled) (.Values.prometheus.grafana.enabled) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: {{ template "monitoring.namespace" . }}
spec:
  replicas: 1
  serviceName: grafana-headless
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        {{- range $key, $val := .Values.prometheus.podLabels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    spec:
      affinity: {{- include "sd.templateValue" ( dict "value" .Values.prometheus.grafana.affinity "context" $ ) | nindent 8 }}
      containers:
        - image: "{{ include "grafana.fullpath" . }}"
          imagePullPolicy: {{ include "resolve.imagePullPolicy" (dict "top" . "specificPullPolicy" .Values.prometheus.pullPolicy) }}
          name: grafana
          ports:
            - containerPort: 3000
              name: grafanaport
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: grafanaport
            initialDelaySeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: grafanaport
            initialDelaySeconds: 10
            failureThreshold: 5 
          resources:
            requests:
              memory: {{.Values.prometheus.grafana.memoryrequested}}
              cpu: {{.Values.prometheus.grafana.cpurequested}}
            limits:
{{- if (.Values.prometheus.grafana.memorylimit ) }}                 
              memory: {{ .Values.prometheus.grafana.memorylimit }}
{{- end }}                  
{{- if (.Values.prometheus.grafana.cpulimit ) }} 
              cpu: {{ .Values.prometheus.grafana.cpulimit }} 
{{- end }}             
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: data
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/all.yaml
              readOnly: true
              subPath: all.yaml
            - name: dashboards
              mountPath: /etc/grafana/provisioning/dashboards/all.yaml
              readOnly: true
              subPath: all.yaml
            - name: kubemetrics
              mountPath: /var/lib/grafana/Kubernetes-SP-metrics.json
              readOnly: true
              subPath: Kubernetes-SP-metrics.json
            - name: selfmonitor
              mountPath: /var/lib/grafana/SA-Self-Monitoring-metrics.json
              readOnly: true
              subPath: SA-Self-Monitoring-metrics.json
{{- if ( .Values.healthcheck.metrics.enabled ) }}
            - name: sd-healthcheckmetrics
              mountPath: /var/lib/grafana/sd-healthcheck-metrics.json
              readOnly: true
              subPath: sd-healthcheck-metrics.json
{{- end }}
{{- if  (.Values.redis.metrics.enabled)  }}
            - name: redismetrics
              mountPath: /var/lib/grafana/Redis-metrics.json
              readOnly: true
              subPath: Redis-metrics.json
{{- end }}
{{- if and ( .Values.kafka.metrics.kafka.enabled ) ( .Values.kafka.metrics.jmx.enabled )  }}
            - name: kafkametrics
              mountPath: /var/lib/grafana/Kafka-metrics.json
              readOnly: true
              subPath: Kafka-metrics.json
{{-  end }}
{{- if (.Values.kafka.zookeeper.metrics.enabled ) }}
            - name: zookeepermetrics
              mountPath: /var/lib/grafana/Zookeeper-metrics.json
              readOnly: true
              subPath: Zookeeper-metrics.json
{{- end }}
      restartPolicy: Always
      volumes:
        - name: data
          emptyDir: {}
        - name: datasources
          configMap:
            defaultMode: 0644
            name: datasources
        - name: dashboards
          configMap:
            defaultMode: 0644
            name: dashboards
        - name: kubemetrics
          configMap:
            defaultMode: 0644
            name: kubemetrics
        - name: selfmonitor
          configMap:
            defaultMode: 0644
            name: selfmonitor
{{- if  (.Values.redis.metrics.enabled)  }}
        - name: redismetrics
          configMap:
            defaultMode: 0644
            name: redismetrics
{{- end }}
{{- if ( .Values.kafka.zookeeper.metrics.enabled ) }}
        - name: zookeepermetrics
          configMap:
            defaultMode: 0644
            name: zookeepermetrics
{{- end }}
{{- if and ( .Values.kafka.metrics.kafka.enabled ) ( .Values.kafka.metrics.jmx.enabled ) }}
        - name: kafkametrics
          configMap:
            defaultMode: 0644
            name: kafkametrics
{{- end }}
{{- if ( .Values.healthcheck.metrics.enabled ) }}
        - name: sd-healthcheckmetrics
          configMap:
            defaultMode: 0644
            name: sd-healthcheckmetrics
{{- end }}
{{- end }}
