{{- if  and  (eq (include "prometheus.enabled" .) "true")  (.Values.prometheus.server_enabled) (.Values.prometheus.grafana.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ template "monitoring.namespace" . }}
spec:
  type: {{ .Values.prometheus.grafanaservicetype | quote }}
  {{- if and (eq .Values.prometheus.grafanaservicetype "LoadBalancer") (not (empty .Values.prometheus.grafanaservicetype)) }}
  loadBalancerIP: {{ .Values.prometheus.grafanaservicetype }}
  {{- end }} 
  ports:
  - port: 3000
    targetPort: 3000
    {{- if and (or (eq .Values.prometheus.grafanaservicetype "NodePort") (eq .Values.prometheus.grafanaservicetype "LoadBalancer")) (not (empty .Values.prometheus.grafananodePort)) }}
    nodePort: {{ .Values.prometheus.grafananodePort }}
    {{- end }}  
  selector:
    app: grafana
{{- end }}