
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: servicedirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.5.2
        imagePullPolicy: IfNotPresent
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-service:9200
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: servicedirector
  labels:
    app: kibana-service
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30033
    name: 5601tcp01 #port to connect to Kibana
  selector:
    app: kibana