version: '2.4'
services:
  db:
    image: oracledb-18xe-sa
    volumes:
      - oradata:/opt/oracle/oradata
  sp:
    image: hub.docker.hpecorp.net/cms-sd/sd-sp:latest
    ports:
      - 8080:8080
    environment:
      - SDCONF_activator_db_hostname=db
      - SDCONF_activator_db_instance=XE
      - SDCONF_activator_db_user=hpsa
      - SDCONF_activator_db_password=secret
      - SDCONF_activator_db_vendor=Oracle
volumes:
  oradata:
    external: false
