version: '2.4'
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --timeout 2 -U $$POSTGRES_USER
      start_period: 10s
      interval: 15s
  couchdb:
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    healthcheck:
      test: curl --fail -s localhost:5984
  sp:
    image: hub.docker.hpecorp.net/cms-sd/sd-sp:latest
    ports:
      - 8081:8080
    volumes:
      - ./logs/sp/activator:/var/opt/OV/ServiceActivator/log
      - ./logs/sp/wildfly:/opt/HP/jboss/standalone/log
    environment:
      - SDCONF_activator_db_hostname=db
      - SDCONF_activator_db_instance=sa
      - SDCONF_activator_db_user=sa
      - SDCONF_activator_db_password=secret
      - SDCONF_activator_db_vendor=PostgreSQL
      - SDCONF_install_asr=yes
      - SDCONF_asr_kafka_brokers=kafka1:9092,kafka2:9092,kafka3:9092
      - SDCONF_asr_zookeeper_nodes=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
  sp-extra:
    image: hub.docker.hpecorp.net/cms-sd/sd-sp:latest
    ports:
      - 8082:8080
    volumes:
      - ./logs/sp-extra/activator:/var/opt/OV/ServiceActivator/log
      - ./logs/sp-extra/wildfly:/opt/HP/jboss/standalone/log
    environment:
      - SDCONF_activator_db_hostname=db
      - SDCONF_activator_db_instance=sa
      - SDCONF_activator_db_user=sa
      - SDCONF_activator_db_password=secret
      - SDCONF_activator_db_vendor=PostgreSQL
      - SDCONF_install_asr=yes
      - SDCONF_asr_kafka_brokers=kafka1:9092,kafka2:9092,kafka3:9092
      - SDCONF_asr_zookeeper_nodes=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
  ui:
    image: hub.docker.hpecorp.net/cms-sd/sd-ui:latest
    ports:
      - 3000:3000
    volumes:
      - ./logs/ui/uoc:/var/opt/uoc2/logs
    environment:
      - SDCONF_sdui_install_assurance=yes
      - SDCONF_sdui_provision_host=sp
      - SDCONF_sdui_async_host=ui
      - SDCONF_uoc_couchdb_host=couchdb
      - SDCONF_uoc_couchdb_admin_username=admin
      - SDCONF_uoc_couchdb_admin_password=admin
  snmpadapter:
    image: hub.docker.hpecorp.net/cms-sd/sd-cl-adapter-snmp:latest
    ports:
      - 162:162/udp
    volumes:
      - ./logs/snmpadapter:/opt/sd-asr/adapter/log
    environment:
      - SDCONF_asr_adapters_bootstrap_servers=kafka1:9092
  kafka1:
    image: bitnami/kafka:3.4.0
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1,zookeeper2,zookeeper3
      - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=60000
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka2:
    image: bitnami/kafka:3.4.0
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1,zookeeper2,zookeeper3
      - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=60000
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka3:
    image: bitnami/kafka:3.4.0
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1,zookeeper2,zookeeper3
      - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=60000
      - ALLOW_PLAINTEXT_LISTENER=yes
  zookeeper1:
    image: bitnami/zookeeper:3.8.1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
  zookeeper2:
    image: bitnami/zookeeper:3.8.1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
  zookeeper3:
    image: bitnami/zookeeper:3.8.1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888

volumes:
  pgdata:
    external: false
