{{- if  (.Values.prometheus.enabled)  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: sd-kube-state-metrics
    app.kubernetes.io/version: v1.8.0
  name: sd-kube-state-metrics
  namespace: {{.Values.monitoringNamespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sd-kube-state-metrics
subjects:
- kind: ServiceAccount
  name: sd-kube-state-metrics
  namespace: {{.Values.monitoringNamespace}}
{{- end }}