{{- if  (eq (include "prometheus.enabled" .) "true")  }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: sd-kube-state-metrics
    app.kubernetes.io/version: v1.8.0
  name: sd-kube-state-metrics
  namespace: {{ template "monitoring.namespace" . }}

{{- end }}