{{- if  (.Values.elk.enabled)  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: {{.Values.monitoringNamespace}}
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch-service
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        resources:
          requests:
            memory: {{.Values.elk.elastic.memoryrequested}}
            cpu: {{.Values.elk.elastic.cpurequested}}
          limits:
{{- if (.Values.elk.elastic.memorylimit ) }}                 
            memory: {{ .Values.elk.elastic.memorylimit }}
{{- end }}                  
{{- if (.Values.elk.elastic.cpulimit ) }} 
            cpu: {{ .Values.elk.elastic.cpulimit }} 
{{- end }}           
        ports:
        - containerPort: 9200
          name: restapi
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-logging
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: elasticsearch-logging
        emptyDir: {}
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
{{- end }}
---
{{- if  (.Values.elk.enabled)  }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: {{.Values.monitoringNamespace}}
  labels:
    app: elasticsearch-service
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: restapi
  selector:
    app: elasticsearch
{{- end }}