version: '2.4'

services:

  db:
    image: containers.enterprisedb.com/edb/edb-as-lite:v11
    environment:
      - ACCEPT_EULA=Yes
      - PGPORT=5444
      - ENTERPRISEDB_PASSWORD=secret
      - DATABASE_NAME=sa
      - DATABASE_USER=sa
      - DATABASE_USER_PASSWORD=secret
    healthcheck:
      test: /var/lib/edb/testIsHealthy.sh
      start_period: 1m
      interval: 15s
    volumes:
      - edb_data:/edbvolume
      - ./edb_initconf:/initconf

  couchdb:
    image: couchdb:2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    healthcheck:
      test: curl --fail -s localhost:5984

  filebeat:
    hostname: filebeat
    image: docker-logs-elk/filebeat:1.0.0
    build:
      context: filebeat
      dockerfile: Dockerfile
    volumes:
      # needed to access additional informations about containers
      - jboss-log:/jboss-log
      - sa-log:/sa-log
      - snmp-log:/snmp-log
      - uoc-log:/uoc-log
      - /var/log/filebeat/:/var/log/filebeat

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    environment:
      - "LOGGING_QUIET=true"
    ports:
      - 5601:5601

  logstash:
    hostname: logstash
    image: docker.elastic.co/logstash/logstash:7.10.1
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    ports:
      - 5044:5044
      - 9600:9600
    environment:
      LOG_LEVEL: error

  elasticsearch:
    hostname: elasticsearch
    image: docker-logs-elk/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 2s
      retries: 5

  sp:
    image: hub.docker.hpecorp.net/cms-sd/sd-sp:latest
    ports:
      - 8080:8080
    volumes:
      - jboss-log:/opt/HP/jboss/standalone/log
      - sa-log:/var/opt/OV/ServiceActivator/log
      - snmp-log:/opt/sd-asr/adapter/log
    environment:
      - SDCONF_activator_db_hostname=db
      - SDCONF_activator_db_instance=sa
      - SDCONF_activator_db_user=sa
      - SDCONF_activator_db_password=secret
      - SDCONF_activator_db_vendor=EnterpriseDB

  ui:
    image: hub.docker.hpecorp.net/cms-sd/sd-ui:latest
    ports:
      - 3000:3000
    volumes:
      - uoc-log:/var/opt/uoc2/logs
    environment:
      - SDCONF_sdui_async_host=ui
      - SDCONF_sdui_provision_host=sp
      - SDCONF_sdui_provision_port=8080
      - SDCONF_sdui_provision_protocol=http
      - SDCONF_uoc_couchdb_host=couchdb
      - SDCONF_uoc_couchdb_admin_username=admin
      - SDCONF_uoc_couchdb_admin_password=admin

volumes:
  jboss-log:
  sa-log:
  snmp-log:
  uoc-log:
  edb_data:
    external: false
