apiVersion: v1
entries:
  sd-helm-chart:
  - apiVersion: v2
    appVersion: 4.2.1
    created: "2022-05-30T14:30:50.627211095+02:00"
    dependencies:
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 14.9.3
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.12
    - condition: couchdb.enabled
      name: couchdb
      repository: https://apache.github.io/couchdb-helm
      version: 3.3.3
    description: Service Director K8s Deployment Scenario for Helm chart
    digest: 8deed1d4ed859cd38869884b372af582cf7cbbc5d8b61bd4a24cb68811521b6a
    icon: https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20PNG/hpe-logo-color.png
    name: sd-helm-chart
    urls:
    - https://github.com/HewlettPackard/hpe-sd-cloud/releases/download/4.2.1/sd-helm-chart-4.2.1.tgz
    version: 4.2.1
  - apiVersion: v2
    appVersion: 4.2.0
    created: "2022-04-29T13:30:19.859003949+02:00"
    dependencies:
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 14.9.3
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.12
    - condition: couchdb.enabled
      name: couchdb
      repository: https://apache.github.io/couchdb-helm
      version: 3.3.3
    description: Service Director K8s Deployment Scenario for Helm chart
    digest: 66a6cc3e7f98750598589111c9bb20afb57dabd724445a3bea787777d33c6db2
    icon: https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20PNG/hpe-logo-color.png
    name: sd-helm-chart
    urls:
    - https://github.com/HewlettPackard/hpe-sd-cloud/releases/download/4.2.0/sd-helm-chart-4.2.0.tgz
    version: 4.2.0
  sd_helm_chart:
  - apiVersion: v2
    appVersion: 4.1.2
    created: "2022-03-31T19:54:01.958189697+02:00"
    dependencies:
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 12.4.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.12
    - condition: couchdb.enabled
      name: couchdb
      repository: https://apache.github.io/couchdb-helm
      version: 3.3.3
    description: Service Director K8s Deployment Scenario for Helm chart
    digest: 2fa861420192ea6b66e26d977d73603ecd5c6aaf9d125e8b024539f1f45eca21
    icon: https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20PNG/hpe-logo-color.png
    name: sd_helm_chart
    urls:
    - https://github.com/HewlettPackard/hpe-sd-cloud/releases/download/4.1.2/sd_helm_chart-4.1.2.tgz
    version: 4.1.2
  - apiVersion: v2
    appVersion: 4.1.1
    created: "2022-03-02T10:41:28.895577121+01:00"
    dependencies:
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 12.4.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.12
    - condition: couchdb.enabled
      name: couchdb
      repository: https://apache.github.io/couchdb-helm
      version: 3.3.2
    description: Service Director K8s Deployment Scenario for Helm chart
    digest: c3889193838cc2c31a1a48e571da09e0cb6ead4ca042c000446d238bbd7b63d5
    icon: https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20PNG/hpe-logo-color.png
    name: sd_helm_chart
    urls:
    - https://github.com/HewlettPackard/hpe-sd-cloud/releases/download/4.1.1/sd_helm_chart-4.1.1.tgz
    version: 4.1.1
  - apiVersion: v2
    appVersion: 4.1.0
    created: "2022-02-02T11:29:53.740310033+01:00"
    dependencies:
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 12.4.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.12
    - condition: couchdb.enabled
      name: couchdb
      repository: https://apache.github.io/couchdb-helm
      version: 3.3.2
    description: Service Director K8s Deployment Scenario for Helm chart
    digest: 05ff236a96d3f51aa1326d6d753d3048f1f2c87127e5405891e9a39bb853ed2c
    icon: https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20PNG/hpe-logo-color.png
    name: sd_helm_chart
    urls:
    - https://github.com/HewlettPackard/hpe-sd-cloud/releases/download/4.1.0/sd_helm_chart-4.1.0.tgz
    version: 4.1.0
  - apiVersion: v2
    appVersion: 4.0.2
    created: "2021-12-22T19:22:40.428146525+01:00"
    dependencies:
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 12.4.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.12
    - condition: couchdb.enabled
      name: couchdb
      repository: https://apache.github.io/couchdb-helm
      version: 3.3.2
    description: Service Director K8s Deployment Scenario for Helm chart
    digest: 0f6ccfe37594198078954d556277766749f2421fcf32a9d4cf72f70873f8c447
    icon: https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20PNG/hpe-logo-color.png
    name: sd_helm_chart
    urls:
    - https://github.com/HewlettPackard/hpe-sd-cloud/releases/download/4.0.2/sd_helm_chart-4.0.2.tgz
    version: 4.0.2
  - apiVersion: v2
    appVersion: 4.0.1
    created: "2021-12-03T11:33:20.836876705+01:00"
    dependencies:
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 12.4.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.12
    - condition: couchdb.enabled
      name: couchdb
      repository: https://apache.github.io/couchdb-helm
      version: 3.3.2
    description: Service Director K8s Deployment Scenario for Helm chart
    digest: 5d6a928b2ae403fc44d6f60119fc4bfde8cec63415c4a31df7f561b4ea8c8576
    icon: https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20PNG/hpe-logo-color.png
    name: sd_helm_chart
    urls:
    - https://github.com/HewlettPackard/hpe-sd-cloud/releases/download/4.0.1/sd_helm_chart-4.0.1.tgz
    version: 4.0.1
  - apiVersion: v2
    appVersion: 4.0.0
    created: "2021-11-03T15:41:42.064876593+01:00"
    dependencies:
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.0.4
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.12
    - condition: couchdb.enabled
      name: couchdb
      repository: https://apache.github.io/couchdb-helm
      version: 3.3.2
    description: Service Director K8s Deployment Scenario for Helm chart
    digest: dd4599bd4113d447ed579ccd9afb70316f8b795ade5ea8383ace28f6a1ed2fb9
    icon: https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20PNG/hpe-logo-color.png
    name: sd_helm_chart
    urls:
    - https://github.com/HewlettPackard/hpe-sd-cloud/releases/download/4.0.0/sd_helm_chart-4.0.0.tgz
    version: 4.0.0
generated: "2022-05-30T14:30:50.595620278+02:00"
