apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-data-volume"
  persistentVolumeReclaimPolicy: Retain
