apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-snmp-adapter
  labels:
    app: sd-snmp-adapter
  namespace: servicedirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-snmp-adapter
  template:
    metadata:
      labels:
        app: sd-snmp-adapter
    spec:
      containers:
      - image: hub.docker.hpecorp.net/cms-sd/sd-cl-adapter-snmp
        imagePullPolicy: Always
        name: sd-snmp-adapter
        env:
        - name: SDCONF_asr_adapters_bootstrap_servers
          value: kafka:9092
        ports:
        - containerPort: 162
          protocol: UDP
          name: 162udp01
        readinessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: 30
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: sd-snmp-adapter-nodeport
  namespace: servicedirector
spec:
  ports:
  - name: 162udp01
    nodePort: 32162
    port: 162
    protocol: UDP
    targetPort: 162
  selector:
    app: sd-snmp-adapter
  sessionAffinity: ClientIP
  type: NodePort
