---
- hosts: localhost
  roles:
    - activator-install
    - solutions-copy
    - kafka-install
    - asr-adapters-install
    - asr-adapters-config
    - nginx-install
    - muse-install
    - role: muse-start
      when: false
    - sdui-muse-install
    - omui-muse-install

  tasks:
    - name: Clean DNF caches
      command:
        cmd: dnf clean all
    - name: Wipe DNF cache directory
      file:
        path: /var/cache/dnf
        state: absent
