---
- hosts: localhost
  roles:
    - activator-install
    - activator-hotfix-copy
    - activator-config
    - activator-hotfix-install
    - solutions-copy
    - kafka-install
    - asr-adapters-install
    - asr-adapters-config
    - uoc-install
    - sdui-install
