{{/*
Create default secrets if they are not set
*/}}

{{- if not (.Values.sdimage.env.SDCONF_activator_db_password_name) }}
{{ include "SD.createdefaultsecret" (dict "all" . "name" "dbsecret" "password" "c2VjcmV0") }}
{{- end }}

{{- if not (.Values.sdui_image.env.SDCONF_sdui_provision_password_name) }}
{{ include "SD.createdefaultsecret" (dict "all" . "name" "provisionsecret" "password" "YWRtaW4wMDE=") }}
{{- end }}