{{- if (and (gt (.Values.deployment_sdsnmp.replicaCount | int) 0) (and (.Values.install_assurance) (.Values.sdsnmp_adapter.enabled) ) ) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment_sdsnmp.name}}
  labels:
    app: {{.Values.deployment_sdsnmp.app}}
  namespace: {{.Release.Namespace}}
spec:
  replicas: {{ .Values.deployment_sdsnmp.replicaCount }}
  selector:
    matchLabels:
      app: {{.Values.deployment_sdsnmp.app}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment_sdsnmp.app}}
        {{- range $key, $val := .Values.deployment_sdsnmp.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end}}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ template "sd-cl.serviceAccount" . }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.deployment_sdsnmp.securityContext.runAsUser | default .Values.securityContext.runAsUser }}
      {{- end }}
      containers:
      - image: "{{ template "sdsnmp_image.fullpath" . }}"
        imagePullPolicy: {{ include "resolve.imagePullPolicy" (dict "top" . "specificPullPolicy" .Values.sdimages.pullPolicy) }}
        name: {{.Values.deployment_sdsnmp.name}}
        env:
        - name: SDCONF_asr_adapters_bootstrap_servers
          value: "{{ .Values.deployment_sdsnmp.env.SDCONF_asr_adapters_bootstrap_servers }}"
        {{- if .Values.deployment_sdsnmp.env_configmap_name }}
        envFrom:
        - configMapRef:
            name: {{ .Values.deployment_sdsnmp.env_configmap_name }}
        {{- end }}
        {{- if .Values.deployment_sdsnmp.env.SDCONF_asr_adapters_manager_port }}
        - name: SDCONF_asr_adapters_manager_port
          value: "{{ .Values.deployment_sdsnmp.env.SDCONF_asr_adapters_manager_port }}"
        {{- end }}
        ports:
        - containerPort: {{ .Values.deployment_sdsnmp.ports.containerPort }}
          protocol: UDP
          name: {{ .Values.deployment_sdsnmp.ports.name }}
        startupProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.deployment_sdsnmp.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.deployment_sdsnmp.startupProbe.periodSeconds }}
        livenessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.deployment_sdsnmp.livenessProbe.failureThreshold }}
          periodSeconds: {{ .Values.deployment_sdsnmp.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.deployment_sdsnmp.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.deployment_sdsnmp.readinessProbe.periodSeconds }}
        resources:
          requests:
            memory: {{.Values.deployment_sdsnmp.memoryrequested}}
            cpu: {{.Values.deployment_sdsnmp.cpurequested}}
          limits:
{{- if (.Values.deployment_sdsnmp.memorylimit ) }}
            memory: {{ .Values.deployment_sdsnmp.memorylimit }}
{{- end }}
{{- if (.Values.deployment_sdsnmp.cpulimit ) }}
            cpu: {{ .Values.deployment_sdsnmp.cpulimit }}
{{- end }}
{{- end }}