# Note that this ingress definition will work with any of the Nginx Ingress Controllers

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sduocingress
  namespace: {{.Release.Namespace}}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end}}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /activator
        pathType: Prefix
        backend:
          service:
          {{- if and (gt (.Values.statefulset_sdsp.replicaCount | int) 0) (not .Values.install_assurance ) }}
            name: {{ .Values.service_sdsp.name }}
            port: 
              number: {{ .Values.service_sdsp.port }}
          {{- end }}
          {{- if and (gt (.Values.statefulset_sdcl.replicaCount | int) 0) (.Values.install_assurance ) }}
            name: {{ .Values.service_sdcl.name }}
            port: 
              number: {{ .Values.service_sdcl.port }}
          {{- end }}
      {{- if and (gt (.Values.sdui_image.replicaCount | int) 0) (.Values.sd_ui_uoc.enabled)  }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service_sdui.name }}
            port: 
              number: {{ .Values.service_sdui.port }}
      {{- end }}
      {{- if and .Values.muse.enabled .Values.muse_gateway.enabled  }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ (include "MUSE.service.fullname"  (dict "all" . "name" .Values.muse_gateway.name )) }}  
            port: 
              number: {{ .Values.muse_gateway.port }}
      {{- end }}
{{- end }}