apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.couchdb.fullnameOverride }}{{ printf "-couchdb" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  adminPassword: YWRtaW4=
  adminUsername: YWRtaW4=
  cookieAuthSecret: eTNOTXZ1N1I1c3VURVZqc1lZWXI=

---


apiVersion: v1
kind: Secret
metadata:
  name: sdsecrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  dbpassword: c2VjcmV0
  provisionpassword: YWRtaW4wMDE=
