{{- if and (not .Values.sdimage.env.SDCONF_activator_db_password_name) (not .Values.sdui_image.env.SDCONF_sdui_provision_password_name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sd-cl.name" . }}-sdsecret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  dbpassword: c2VjcmV0
  provisionpassword: YWRtaW4wMDE=
{{- end }}