{{- if or (gt (.Values.statefulset_sdsp.replicaCount | int) 0) (gt (.Values.statefulset_sdcl.replicaCount | int) 0) }}
# SD-SP, SD-CL Service
---
{{ include "sd-helm-chart.sdsp.service" . }}

{{- if (.Values.prometheus.enabled) }}
# SD-SP Prometheus Service
---
{{ include "sd-helm-chart.sdsp.service.prometheus" . }}
{{- end }}

{{- if ( .Values.sdui_image.loadbalancer) }}
# SD-SP Headless Service
---
{{ include "sd-helm-chart.sdsp.service.headless" . }}
{{- end }}
{{- end }}
