{{- if or (gt (.Values.statefulset_sdsp.replicaCount | int) 0) (gt (.Values.statefulset_sdcl.replicaCount | int) 0) }}
# SD-SP, SD-CL Service
---
{{ include "sd-helm-chart.sdsp.service" . }}

{{- if or (eq (include "prometheus.enabled" .) "true") (.Values.sdimage.metrics.enabled) }}
# SD-SP Envoy Service
---
{{ include "sd-helm-chart.sdsp.service.envoy" . }}
{{- end }}

{{- if ( .Values.sdui_image.loadbalancer) }}
# SD-SP Headless Service
---
{{ include "sd-helm-chart.sdsp.service.headless" . }}
{{- end }}
{{- end }}
