{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sd-cl.serviceAccount" . }}
  {{- if (.Values.servicedirectorNamespace) }}
  namespace: {{ .Values.servicedirectorNamespace | quote }}
  {{- end }}      
  labels:
    app: {{ template "sd-cl.name" . }}
    chart: {{ template "sd-cl.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.serviceAccount.imagePullSecrets }}
{{- end }}
{{- end }}
