{{- if and (gt (.Values.statefulset_sdcl.replicaCount | int) 0) (.Values.sdimage.install_assurance )  }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulset_sdcl.name}}
  labels:
    app: {{.Values.statefulset_sdcl.app}}
  namespace: {{.Values.servicedirectorNamespace}}
spec:
  replicas: {{ .Values.statefulset_sdcl.replicaCount }}
  serviceName: {{.Values.statefulset_sdcl.servicename}}
  selector:
    matchLabels:
      app: {{.Values.statefulset_sdcl.app}}
  template:
    metadata:
      labels:
        app: {{.Values.statefulset_sdcl.app}}
    spec:
      containers:
      - image: "{{ .Values.statefulset_sdcl.image.repository | default .Values.sdimage.repository }}{{ .Values.statefulset_sdcl.image.name }}:{{ .Values.statefulset_sdcl.image.tag | default .Values.sdimage.version }}"
        imagePullPolicy: {{ .Values.sdimage.pullPolicy }}
        name: {{.Values.statefulset_sdcl.servicename}}
        env:
        - name: SDCONF_activator_db_vendor
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_vendor }}"
        - name: SDCONF_activator_db_hostname
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_hostname }}"
        - name: SDCONF_activator_db_instance
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_instance }}"
        - name: SDCONF_activator_db_user
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_user }}"
        - name: SDCONF_activator_db_password
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.sdimage.env.SDCONF_activator_db_password_key }}"            
              name: "{{ .Values.sdimage.env.SDCONF_activator_db_password_name }}"
        - name: SDCONF_asr_kafka_brokers
          value: "{{ .Values.statefulset_sdcl.env.SDCONF_asr_kafka_brokers }}"
        - name: SDCONF_asr_zookeeper_nodes
          value: "{{ .Values.statefulset_sdcl.env.SDCONF_asr_zookeeper_nodes }}"
        - name: SDCONF_install_asr
          value: "yes"
        - name: SDCONF_asr_node
          value: "yes"
        - name: SDCONF_asr_only_node
          value: "no"
        ports:
        - containerPort: {{ .Values.statefulset_sdcl.ports.containerPort }}
          name: {{ .Values.statefulset_sdcl.ports.name }}
        startupProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdcl.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdcl.startupProbe.periodSeconds }}     
        livenessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdcl.livenessProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdcl.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdcl.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdcl.readinessProbe.periodSeconds }}
       
        resources:
          requests:
            memory: {{ .Values.sdimage.memoryrequested }}
            cpu: {{ .Values.sdimage.cpurequested }}
          limits:
{{- if (.Values.sdimage.memorylimit ) }}                 
            memory: {{ .Values.sdimage.memorylimit }}
{{- end }}                  
{{- if (.Values.sdimage.cpulimit ) }} 
            cpu: {{ .Values.sdimage.cpulimit }} 
{{- end }}    
        {{- with .Values.sdimage.affinity }}
        affinity:
{{ tpl (toYaml .) $ | indent 10 }}
        {{- end }} 
        {{- with .Values.sdimage.topologySpreadConstraints }}
        topologySpreadConstraints:
{{ tpl (toYaml .) $ | indent 10 }}
        {{- end }}                 
{{- if  (.Values.licenseEnabled) }}
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - cp /mnt/license /license
{{- end }}
        volumeMounts:
{{- if  (.Values.licenseEnabled) }}
        - name: sd-license
          mountPath: "/mnt"
          readOnly: true
{{- end }}
{{- if  or (.Values.prometheus.enabled) (.Values.elk.enabled)  }}
        - name: jboss-log
          mountPath: /opt/HP/jboss/standalone/log/
        - name: sa-log
          mountPath: /var/opt/OV/ServiceActivator/log/
        - name: snmp-log
          mountPath: /opt/sd-asr/adapter/log/
{{- end }}
{{- if  (.Values.prometheus.enabled)  }}
        - name: wfconfig
          mountPath: /etc/opt/OV/ServiceActivator/config/mwfm/config-selfmonitor.xml
          readOnly: true
          subPath: config.xml
        - name: alarms-log
          mountPath: /var/opt/OV/ServiceActivator/alarms/
{{- end }}



{{- if  (.Values.prometheus.enabled)  }}
      - name: grok-exporter
        image: "{{ include "grokrepository.fullpath" . }}"     
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        ports:
        - containerPort: 9144
          name: 9144tcp01
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9144tcp01
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9144tcp01
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60    
{{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
{{- end }}                
        resources:
          requests:
            memory: {{ .Values.sdimage.grokexporter.memoryrequested }}
            cpu: {{ .Values.sdimage.grokexporter.cpurequested }}
          limits:
{{- if (.Values.sdimage.grokexporter.memorylimit ) }}                 
            memory: {{ .Values.sdimage.grokexporter.memorylimit }}
{{- end }}                  
{{- if (.Values.sdimage.grokexporter.cpulimit ) }} 
            cpu: {{ .Values.sdimage.grokexporter.cpulimit }} 
{{- end }} 
        volumeMounts:
        - name: alarms-log
          mountPath: /alarms-log/
          subPathExpr: $(POD_NAME)
        - name: config
          mountPath: /grok/config.yml
          readOnly: true
          subPath: config.yml
{{- end }}



{{- if  (.Values.elk.enabled)  }}
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:{{.Values.elk.version}}
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        ports:
          - name: filebeat-http
            containerPort: 5066
            protocol: TCP
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                curl --fail 127.0.0.1:5066
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                filebeat test config
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5 
{{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
{{- end }}
        resources:
          requests:
            memory: {{ .Values.sdimage.filebeat.memoryrequested }}
            cpu: {{ .Values.sdimage.filebeat.cpurequested }}
          limits:
{{- if (.Values.sdimage.filebeat.memorylimit ) }}                 
            memory: {{ .Values.sdimage.filebeat.memorylimit }}
{{- end }}                  
{{- if (.Values.sdimage.filebeat.cpulimit ) }} 
            cpu: {{ .Values.sdimage.filebeat.cpulimit }} 
{{- end }}

        volumeMounts:
        - name: jboss-log
          mountPath: /jboss-log
        - name: sa-log
          mountPath: /sa-log
          subPathExpr: $(POD_NAME)
        - name: snmp-log
          mountPath: /snmp-log
        # needed to access additional informations about containers
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # needed to access additional informations about containers
        - name: filebeatconfig
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log/filebeat
{{- end }}


      volumes:
{{- if  (.Values.licenseEnabled) }}
      - name: sd-license
        secret:
          secretName: sd-license-secret
{{- end }}
{{- if  (.Values.prometheus.enabled)  }}
      - name: wfconfig
        configMap:
          defaultMode: 0644
          name: wf-config
      - name: config
        configMap:
          defaultMode: 0644
          name: grok-config
      - name: alarms-log
        emptyDir: {}
{{- end }}
{{- if  (.Values.elk.enabled)  }}
      - name: filebeatconfig
        configMap:
          defaultMode: 0644
          name: filebeat-config
      - name: varlog
        emptyDir: {}
      - name: data
        emptyDir: {}
{{- end }}
{{- if  or (.Values.elk.enabled)   (.Values.prometheus.enabled) }}
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: jboss-log
        emptyDir: {}
      - name: sa-log
        emptyDir: {}
      - name: snmp-log
        emptyDir: {}
{{- end }}
{{- end }}
---
{{- if and (gt (.Values.statefulset_sdcl.replicaCount_asr_only | int) 0) (.Values.sdimage.install_assurance )  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulset_sdcl.servicename_asr_only}}
  labels:
    app: {{.Values.statefulset_sdcl.app}}
  namespace: {{.Values.servicedirectorNamespace}}
spec:
  replicas: {{ .Values.statefulset_sdcl.replicaCount_asr_only }}
  serviceName: {{.Values.statefulset_sdcl.servicename_asr_only}}
  selector:
    matchLabels:
      app: {{.Values.statefulset_sdcl.app}}
  template:
    metadata:
      labels:
        app: {{.Values.statefulset_sdcl.app}}
    spec:
      containers:
      - image: "{{ .Values.statefulset_sdcl.image.repository | default .Values.sdimage.repository }}{{ .Values.statefulset_sdcl.image.name }}:{{ .Values.statefulset_sdcl.image.tag | default .Values.sdimage.version }}"
        imagePullPolicy: {{ .Values.sdimage.pullPolicy }}
        name: {{.Values.statefulset_sdcl.servicename_asr_only}}
        env:
        - name: SDCONF_activator_db_vendor
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_vendor }}"
        - name: SDCONF_activator_db_hostname
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_hostname }}"
        - name: SDCONF_activator_db_instance
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_instance }}"
        - name: SDCONF_activator_db_user
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_user }}"
        - name: SDCONF_activator_db_password
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.sdimage.env.SDCONF_activator_db_password_key }}"            
              name: "{{ .Values.sdimage.env.SDCONF_activator_db_password_name }}"
        - name: SDCONF_asr_kafka_brokers
          value: "{{ .Values.statefulset_sdcl.env.SDCONF_asr_kafka_brokers }}"
        - name: SDCONF_asr_zookeeper_nodes
          value: "{{ .Values.statefulset_sdcl.env.SDCONF_asr_zookeeper_nodes }}"
        - name: SDCONF_install_asr
          value: "yes"
        - name: SDCONF_asr_node
          value: "yes"
        - name: SDCONF_asr_only_node
          value: "yes"
        ports:
        - containerPort: {{ .Values.statefulset_sdcl.ports.containerPort }}
          name: {{ .Values.statefulset_sdcl.ports.name }}
        livenessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: 360
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: 180
          periodSeconds: 15
        
        resources:
          requests:
            memory: {{ .Values.sdimage.memoryrequested }}
            cpu: {{ .Values.sdimage.cpurequested }}
          limits:
{{- if (.Values.sdimage.grokexporter.memorylimit ) }}                 
            memory: {{ .Values.sdimage.grokexporter.memorylimit }}
{{- end }}                  
{{- if (.Values.sdimage.grokexporter.cpulimit ) }} 
            cpu: {{ .Values.sdimage.grokexporter.cpulimit }} 
{{- end }}        
        {{- with .Values.sdimage.affinity }}
        affinity:
{{ tpl (toYaml .) $ | indent 10 }}
        {{- end }}       
        {{- with .Values.sdimage.topologySpreadConstraints }}
        topologySpreadConstraints:
{{ tpl (toYaml .) $ | indent 10 }}
        {{- end }}              
{{- if  (.Values.licenseEnabled) }}
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - cp /mnt/license /license
{{- end }}
        volumeMounts:
{{- if  (.Values.licenseEnabled) }}
        - name: sd-license
          mountPath: "/mnt"
          readOnly: true
{{- end }}
{{- if  or (.Values.prometheus.enabled) (.Values.elk.enabled)  }}
        - name: jboss-log
          mountPath: /opt/HP/jboss/standalone/log/
        - name: sa-log
          mountPath: /var/opt/OV/ServiceActivator/log/
        - name: snmp-log
          mountPath: /opt/sd-asr/adapter/log/
{{- end }}
{{- if  (.Values.prometheus.enabled)  }}
        - name: wfconfig
          mountPath: /etc/opt/OV/ServiceActivator/config/mwfm/config-selfmonitor.xml
          readOnly: true
          subPath: config.xml
        - name: alarms-log
          mountPath: /var/opt/OV/ServiceActivator/alarms/
{{- end }}



{{- if  (.Values.prometheus.enabled)  }}
      - name: grok-exporter
        image: "{{ include "grokrepository.fullpath" . }}"    
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        ports:
        - containerPort: 9144
          name: 9144tcp01
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9144tcp01
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9144tcp01
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60          
{{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
{{- end }}          
        resources:
          requests:
            memory: {{ .Values.sdimage.grokexporter.memoryrequested }}
            cpu: {{ .Values.sdimage.grokexporter.cpurequested }}
          limits:
{{- if (.Values.sdimage.grokexporter.memorylimit ) }}                 
            memory: {{ .Values.sdimage.grokexporter.memorylimit }}
{{- end }}                  
{{- if (.Values.sdimage.grokexporter.cpulimit ) }} 
            cpu: {{ .Values.sdimage.grokexporter.cpulimit }} 
{{- end }}
        volumeMounts:
        - name: alarms-log
          mountPath: /alarms-log/
          subPathExpr: $(POD_NAME)
        - name: config
          mountPath: /grok/config.yml
          readOnly: true
          subPath: config.yml
{{- end }}


{{- if  (.Values.elk.enabled)  }}
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:{{.Values.elk.version}}
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        ports:
          - name: filebeat-http
            containerPort: 5066
            protocol: TCP
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                curl --fail 127.0.0.1:5066
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                filebeat test config
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5    
{{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
{{- end }}              
        resources:
          requests:
            memory: {{ .Values.sdimage.filebeat.memoryrequested }}
            cpu: {{ .Values.sdimage.filebeat.cpurequested }}
          limits:
{{- if (.Values.sdimage.filebeat.memorylimit ) }}                 
            memory: {{ .Values.sdimage.filebeat.memorylimit }}
{{- end }}                  
{{- if (.Values.sdimage.filebeat.cpulimit ) }} 
            cpu: {{ .Values.sdimage.filebeat.cpulimit }} 
{{- end }}  


        volumeMounts:
        - name: jboss-log
          mountPath: /jboss-log
        - name: sa-log
          mountPath: /sa-log
          subPathExpr: $(POD_NAME)
        - name: snmp-log
          mountPath: /snmp-log
        # needed to access additional informations about containers
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # needed to access additional informations about containers
        - name: filebeatconfig
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log/filebeat
{{- end }}

      volumes:
{{- if  (.Values.licenseEnabled) }}
      - name: sd-license
        secret:
          secretName: sd-license-secret
{{- end }}
{{- if  (.Values.prometheus.enabled)  }}
      - name: wfconfig
        configMap:
          defaultMode: 0644
          name: wf-config
      - name: config
        configMap:
          defaultMode: 0644
          name: grok-config
      - name: alarms-log
        emptyDir: {}
{{- end }}
{{- if  (.Values.elk.enabled)  }}
      - name: filebeatconfig
        configMap:
          defaultMode: 0644
          name: filebeat-config
      - name: varlog
        emptyDir: {}
      - name: data
        emptyDir: {}
{{- end }}
{{- if  or (.Values.elk.enabled)   (.Values.prometheus.enabled) }}
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: jboss-log
        emptyDir: {}
      - name: sa-log
        emptyDir: {}
      - name: snmp-log
        emptyDir: {}
{{- end }}
{{- end }}
