{{- if and (gt (.Values.statefulset_sdsp.replicaCount | int) 0)  (not .Values.sdimage.install_assurance )  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulset_sdsp.name}}
  labels:
    app: {{.Values.statefulset_sdsp.app}}
  namespace: {{.Values.servicedirectorNamespace}}
spec:
  replicas: {{ .Values.statefulset_sdsp.replicaCount }}
  serviceName: {{.Values.statefulset_sdsp.servicename}}
  selector:
    matchLabels:
      app: {{.Values.statefulset_sdsp.app}}
  template:
    metadata:
      labels:
        app: {{.Values.statefulset_sdsp.app}}
    spec:
      containers:
      - image: "{{ .Values.statefulset_sdsp.image.repository | default .Values.sdimage.repository }}{{ .Values.statefulset_sdsp.image.name }}:{{ .Values.statefulset_sdsp.image.tag | default .Values.sdimage.version }}"
        imagePullPolicy: {{ .Values.sdimage.pullPolicy }}
        name: {{.Values.statefulset_sdsp.servicename}}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name         
        - name: SDCONF_activator_db_vendor
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_vendor }}"
        - name: SDCONF_activator_db_hostname
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_hostname }}"
        - name: SDCONF_activator_db_instance
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_instance }}"
        - name: SDCONF_activator_db_user
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_user }}"
        - name: SDCONF_activator_db_password
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.sdimage.env.SDCONF_activator_db_password_key }}"            
              name: "{{ .Values.sdimage.env.SDCONF_activator_db_password_name }}"
{{- if (.Values.sdimage.env.SDCONF_activator_conf_jvm_max_memory ) }}                 
        - name: SDCONF_activator_conf_jvm_max_memory
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_jvm_max_memory }}"
{{- end }}          
{{- if (.Values.sdimage.env.SDCONF_activator_conf_jvm_min_memory ) }}                 
        - name: SDCONF_activator_conf_jvm_min_memory
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_jvm_min_memory }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_activation_max_threads ) }}                 
        - name: SDCONF_activator_conf_activation_max_threads
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_activation_max_threads }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_activation_min_threads ) }}                 
        - name: SDCONF_activator_conf_activation_min_threads
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_activation_min_threads }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_defaultdb_max ) }}                 
        - name: SDCONF_activator_conf_pool_defaultdb_max
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_defaultdb_max }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_defaultdb_min ) }}                 
        - name: SDCONF_activator_conf_pool_defaultdb_min
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_defaultdb_min }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_inventorydb_max ) }}                 
        - name: SDCONF_activator_conf_pool_inventorydb_max
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_inventorydb_max }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_inventorydb_min ) }}                 
        - name: SDCONF_activator_conf_pool_inventorydb_min
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_inventorydb_min }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_mwfmdb_max ) }}                 
        - name: SDCONF_activator_conf_pool_mwfmdb_max
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_mwfmdb_max }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_mwfmdb_min ) }}                 
        - name: SDCONF_activator_conf_pool_mwfmdb_min
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_mwfmdb_min }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_resmgrdb_max ) }}                 
        - name: SDCONF_activator_conf_pool_resmgrdb_max
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_resmgrdb_max }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_resmgrdb_min ) }}                 
        - name: SDCONF_activator_conf_pool_resmgrdb_min
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_resmgrdb_min }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_servicedb_max ) }}                 
        - name: SDCONF_activator_conf_pool_servicedb_max
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_servicedb_max }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_servicedb_min ) }}                 
        - name: SDCONF_activator_conf_pool_servicedb_min
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_servicedb_min }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_uidb_max ) }}                 
        - name: SDCONF_activator_conf_pool_uidb_max
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_uidb_max }}"
{{- end }}  
{{- if (.Values.sdimage.env.SDCONF_activator_conf_pool_uidb_min ) }}                 
        - name: SDCONF_activator_conf_pool_uidb_min
          value: "{{ .Values.sdimage.env.SDCONF_activator_conf_pool_uidb_min }}"
{{- end }}                
        ports:
        - containerPort: {{ .Values.statefulset_sdsp.ports.containerPort }}
          name: {{ .Values.statefulset_sdsp.ports.name }}
        startupProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdsp.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdsp.startupProbe.periodSeconds }}     
        livenessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdsp.livenessProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdsp.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdsp.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdsp.readinessProbe.periodSeconds }}
 
        resources:
          requests:
            memory: {{ .Values.sdimage.memoryrequested }}
            cpu: {{ .Values.sdimage.cpurequested }}
          limits:
{{- if (.Values.sdimage.memorylimit ) }}                 
            memory: {{ .Values.sdimage.memorylimit }}
{{- end }}                  
{{- if (.Values.sdimage.cpulimit ) }} 
            cpu: {{ .Values.sdimage.cpulimit }} 
{{- end }}          
        {{- with .Values.sdimage.affinity }}
        affinity:
{{ tpl (toYaml .) $ | indent 10 }}
        {{- end }}   
        {{- with .Values.sdimage.topologySpreadConstraints }}
        topologySpreadConstraints:
{{ tpl (toYaml .) $ | indent 10 }}
        {{- end }}                   
{{- if  (.Values.licenseEnabled) }}
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - cp /mnt/license /license
{{- end }}
        volumeMounts:
{{- if  (.Values.licenseEnabled) }}
        - name: sd-license
          mountPath: "/mnt"
          readOnly: true
{{- end }}
{{- if  or (.Values.prometheus.enabled) (.Values.elk.enabled)  }}
        - name: jboss-log
          mountPath: /opt/HP/jboss/standalone/log/
        - name: sa-log
          mountPath: /var/opt/OV/ServiceActivator/log/
        - name: snmp-log
          mountPath: /opt/sd-asr/adapter/log/
{{- end }}
{{- if  (.Values.prometheus.enabled)  }}
        - name: wfconfig
          mountPath: /etc/opt/OV/ServiceActivator/config/mwfm/config-selfmonitor.xml
          readOnly: true
          subPath: config.xml
        - name: alarms-log
          mountPath: /var/opt/OV/ServiceActivator/alarms/
        - name: public-mng-interface
          mountPath: /docker/scripts/startup/02_public_ifaces.sh
          subPath: 02_public_ifaces.sh

{{- end }}


{{- if  (.Values.prometheus.enabled)  }}
      - name: grok-exporter
        image: "{{ include "grokrepository.fullpath" . }}"       
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        ports:
        - containerPort: 9144
          name: 9144tcp01
        startupProbe:
          httpGet:  
            path: /metrics
            port: 9144tcp01
          failureThreshold: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9144tcp01
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9144tcp01
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60
{{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
{{- end }}          
        resources:
          requests:
            memory: {{ .Values.sdimage.grokexporter.memoryrequested }}
            cpu: {{ .Values.sdimage.grokexporter.cpurequested }}
          limits:
{{- if (.Values.sdimage.grokexporter.memorylimit ) }}                 
            memory: {{ .Values.sdimage.grokexporter.memorylimit }}
{{- end }}                  
{{- if (.Values.sdimage.grokexporter.cpulimit ) }} 
            cpu: {{ .Values.sdimage.grokexporter.cpulimit }} 
{{- end }}     
        volumeMounts:
        - name: alarms-log
          mountPath: /alarms-log/
          subPathExpr: $(POD_NAME)
        - name: config
          mountPath: /grok/config.yml
          readOnly: true
          subPath: config.yml
{{- end }}


{{- if  (.Values.elk.enabled)  }}
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:{{.Values.elk.version}}
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        ports:
          - name: filebeat-http
            containerPort: 5066
            protocol: TCP
        startupProbe:
          exec:
            command:
              - sh
              - -c 
              - |
                #!/usr/bin/env bash -e
                filebeat test config
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                curl --fail 127.0.0.1:5066
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                filebeat test config
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5      
{{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
{{- end }}
        resources:
          requests:
            memory: {{ .Values.sdimage.filebeat.memoryrequested }}
            cpu: {{ .Values.sdimage.filebeat.cpurequested }}
          limits:
{{- if (.Values.sdimage.filebeat.memorylimit ) }}                 
            memory: {{ .Values.sdimage.filebeat.memorylimit }}
{{- end }}                  
{{- if (.Values.sdimage.filebeat.cpulimit ) }} 
            cpu: {{ .Values.sdimage.filebeat.cpulimit }} 
{{- end }}           

        volumeMounts:
        - name: jboss-log
          mountPath: /jboss-log
        - name: sa-log
          mountPath: /sa-log
          subPathExpr: $(POD_NAME)
        - name: snmp-log
          mountPath: /snmp-log
        # needed to access additional informations about containers
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # needed to access additional informations about containers
        - name: filebeatconfig
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log/filebeat
{{- end }}

      volumes:
{{- if  (.Values.licenseEnabled) }}
      - name: sd-license
        secret:
          secretName: sd-license-secret
{{- end }}
{{- if  (.Values.prometheus.enabled)  }}
      - name: wfconfig
        configMap:
          defaultMode: 0644
          name: wf-config
      - name: public-mng-interface
        configMap:
          defaultMode: 0644
          name: public-mng-interface
      - name: config
        configMap:
          defaultMode: 0644
          name: grok-config
      - name: alarms-log
        emptyDir: {}
{{- end }}
{{- if  (.Values.elk.enabled)  }}
      - name: filebeatconfig
        configMap:
          defaultMode: 0644
          name: filebeat-config
      - name: varlog
        emptyDir: {}
      - name: data
        emptyDir: {}
{{- end }}
{{- if  or (.Values.elk.enabled)   (.Values.prometheus.enabled) }}
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: jboss-log
        emptyDir: {}
      - name: sa-log
        emptyDir: {}
      - name: snmp-log
        emptyDir: {}
{{- end }}
{{- end }}
