{{- if and (gt (.Values.statefulset_sdui_cl.replicaCount | int) 0) (.Values.sdimage.install_assurance) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulset_sdui_cl.name}}
  labels:
    app: {{.Values.statefulset_sdui_cl.app}}
  namespace: {{.Values.servicedirectorNamespace}}
spec:
  replicas: {{ .Values.statefulset_sdui_cl.replicaCount }}
  serviceName: {{.Values.statefulset_sdui.servicename}}
  selector:
    matchLabels:
      app: {{.Values.statefulset_sdui_cl.app}}
  template:
    metadata:
      labels:
        app: {{.Values.statefulset_sdui_cl.app}}
    spec:
      containers:
      - image: "{{ .Values.statefulset_sdui_cl.image.repository | default .Values.sdimage.repository }}{{ .Values.statefulset_sdui_cl.image.name }}:{{ .Values.statefulset_sdui_cl.image.tag | default .Values.sdimage.version }}"
        imagePullPolicy: {{ .Values.sdimage.pullPolicy }}
        name: {{.Values.statefulset_sdui_cl.name}}
        env:
        - name: SDCONF_sdui_async_host
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
{{- if (.Values.sdui_image.loadbalancer) }}
        - name: SDCONF_sdui_provision_host
          value: "envoy"
        - name: SDCONF_sdui_provision_port
          value: "30636"
{{- else }}
        - name: SDCONF_sdui_provision_host
          value: "{{ .Values.service_sdcl.name }}"
        - name: SDCONF_sdui_provision_port
          value: "{{ .Values.service_sdcl.port }}"
{{- end }}

        - name: SDCONF_sdui_provision_password
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.statefulset_sdui.env.SDCONF_sdui_provision_password_key }}"
              name: "{{ .Values.statefulset_sdui.env.SDCONF_sdui_provision_password_name }}"
        - name: SDCONF_sdui_provision_protocol
          value: "{{ .Values.statefulset_sdui_cl.env.SDCONF_sdui_provision_protocol }}"
        - name: SDCONF_sdui_provision_tenant
          value: "{{ .Values.statefulset_sdui_cl.env.SDCONF_sdui_provision_tenant }}"
        - name: SDCONF_sdui_provision_use_real_user
          value: "{{ .Values.statefulset_sdui_cl.env.SDCONF_sdui_provision_use_real_user }}"
        - name: SDCONF_sdui_provision_username
          value: "{{ .Values.statefulset_sdui_cl.env.SDCONF_sdui_provision_username }}"
        - name: SDCONF_sdui_assurance_host
          value: "{{ .Values.service_sdcl.name }}"
        - name: SDCONF_sdui_install_assurance
          value: "{{ .Values.sdimage.install_assurance }}"
        - name: SDCONF_uoc_couchdb_host
          value: "{{ .Values.statefulset_sdui_cl.env.SDCONF_uoc_couchdb_host }}"
        - name: SDCONF_uoc_couchdb_admin_username
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.statefulset_sdui.env.SDCONF_uoc_couchdb_admin_username_key }}"
              name: "{{ .Values.statefulset_sdui.env.SDCONF_uoc_couchdb_admin_username_name }}"
        - name: SDCONF_uoc_couchdb_admin_password
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.statefulset_sdui.env.SDCONF_uoc_couchdb_admin_password_key }}"
              name: "{{ .Values.statefulset_sdui.env.SDCONF_uoc_couchdb_admin_password_name }}"
        - name: SDCONF_sdui_redis
          value: "yes"
        - name: SDCONF_sdui_redis_host
          value: "{{ .Values.redis.fullnameOverride }}{{ printf "-master" }}"
        - name: SDCONF_sdui_redis_port
          value: "{{ .Values.redis.redisPort }}"
        - name: SDCONF_sdui_redis_password
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.redis.existingSecret }}"
              key: "{{ .Values.redis.existingSecretPasswordKey }}"
        ports:
        - containerPort: {{ .Values.statefulset_sdui_cl.ports.containerPort }}
          name: {{ .Values.statefulset_sdui_cl.ports.name }}
        startupProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdui_cl.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdui_cl.startupProbe.periodSeconds }}  
        livenessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdui_cl.livenessProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdui_cl.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdui_cl.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdui_cl.readinessProbe.periodSeconds }}
        resources:
          requests:
            memory: {{ .Values.sdui_image.memoryrequested }}
            cpu: {{ .Values.sdui_image.cpurequested }}
          limits:
{{- if (.Values.sdui_image.memorylimit) }}
            memory: {{ .Values.sdui_image.memorylimit }}
{{- end }}
{{- if (.Values.sdui_image.cpulimit) }}
            cpu: {{ .Values.sdui_image.cpulimit }}
{{- end }}
{{- if (.Values.elk.enabled) }}
        volumeMounts:
        - name: uoc-log
          mountPath: /var/opt/uoc2/logs
{{- end }}
{{- if (.Values.sdui_image.loadbalancer) }}
      - name: envoy
        image: bitnami/envoy:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: frontend
          timeoutSeconds: 1
        ports:
        - containerPort: 30636
          name: frontend
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/bitnami/envoy/conf/
          name: envoy-config
{{- end }}
{{- if (.Values.elk.enabled) }}
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:{{.Values.elk.version}}
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        ports:
          - name: filebeat-http
            containerPort: 5066
            protocol: TCP
        startupProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                filebeat test config
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                curl --fail 127.0.0.1:5066
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                filebeat test config
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
{{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
{{- end }}
        resources:
          requests:
            memory: {{ .Values.sdui_image.filebeat.memoryrequested }}
            cpu: {{ .Values.sdui_image.filebeat.cpurequested }}
          limits:
{{- if (.Values.sdui_image.filebeat.memorylimit) }}
            memory: {{ .Values.sdui_image.filebeat.memorylimit }}
{{- end }}
{{- if (.Values.sdui_image.filebeat.cpulimit) }}
            cpu: {{ .Values.sdui_image.filebeat.cpulimit }}
{{- end }}
        volumeMounts:
        # needed to access additional informations about containers
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
          subPathExpr: $(POD_NAME)
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log/filebeat
        - name: uoc-log
          mountPath: /uoc-log
{{- end }}

      volumes:

{{- if (.Values.elk.enabled) }}
      - name: config
        configMap:
          defaultMode: 0644
          name: filebeat-config-ui
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        emptyDir: {}
      # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
      - name: data
        emptyDir: {}
      - name: uoc-log
        emptyDir: {}
{{- end }}
{{- if (.Values.sdui_image.loadbalancer) }}
      - configMap:
          defaultMode: 420
          name: envoy
        name: envoy-config
{{- end }}
      imagePullSecrets:
      - name: "{{ .Values.redis.existingSecret }}"
{{- end }}

{{- if and (gt (.Values.statefulset_sdui.replicaCount | int) 0) (not .Values.sdimage.install_assurance) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulset_sdui.name}}
  labels:
    app: {{.Values.statefulset_sdui.app}}
  namespace: {{.Values.servicedirectorNamespace}}
spec:
  replicas: {{ .Values.statefulset_sdui.replicaCount }}
  serviceName: {{ .Values.statefulset_sdui.servicename }}
  selector:
    matchLabels:
      app: {{.Values.statefulset_sdui.app}}
  template:
    metadata:
      labels:
        app: {{.Values.statefulset_sdui.app}}
    spec:
      containers:
      - image: "{{ .Values.statefulset_sdui.image.repository | default .Values.sdimage.repository }}{{ .Values.statefulset_sdui.image.name }}:{{ .Values.statefulset_sdui.image.tag | default .Values.sdimage.version }}"
        imagePullPolicy: {{ .Values.sdimage.pullPolicy }}
        name: {{.Values.statefulset_sdui.name}}
        env:
        - name: SDCONF_sdui_async_host
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
{{- if (.Values.sdui_image.loadbalancer) }}
        - name: SDCONF_sdui_provision_host
          value: "envoy"
        - name: SDCONF_sdui_provision_port
          value: "30636"
{{- else }}
        - name: SDCONF_sdui_provision_host
          value: "{{ .Values.service_sdsp.name }}"
        - name: SDCONF_sdui_provision_port
          value: "{{ .Values.service_sdsp.port }}"
{{- end }}

        - name: SDCONF_sdui_provision_password
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.statefulset_sdui.env.SDCONF_sdui_provision_password_key }}"
              name: "{{ .Values.statefulset_sdui.env.SDCONF_sdui_provision_password_name }}"
        - name: SDCONF_sdui_provision_protocol
          value: "{{ .Values.statefulset_sdui.env.SDCONF_sdui_provision_protocol }}"
        - name: SDCONF_sdui_provision_tenant
          value: "{{ .Values.statefulset_sdui.env.SDCONF_sdui_provision_tenant }}"
        - name: SDCONF_sdui_provision_use_real_user
          value: "{{ .Values.statefulset_sdui.env.SDCONF_sdui_provision_use_real_user }}"
        - name: SDCONF_sdui_provision_username
          value: "{{ .Values.statefulset_sdui.env.SDCONF_sdui_provision_username }}"
        - name: SDCONF_sdui_install_assurance
          value: "{{ .Values.sdimage.install_assurance }}"
        - name: SDCONF_uoc_couchdb_host
          value: "{{ .Values.statefulset_sdui.env.SDCONF_uoc_couchdb_host }}"
        - name: SDCONF_uoc_couchdb_admin_username
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.statefulset_sdui.env.SDCONF_uoc_couchdb_admin_username_key }}"
              name: "{{ .Values.statefulset_sdui.env.SDCONF_uoc_couchdb_admin_username_name }}"
        - name: SDCONF_uoc_couchdb_admin_password
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.statefulset_sdui.env.SDCONF_uoc_couchdb_admin_password_key }}"
              name: "{{ .Values.statefulset_sdui.env.SDCONF_uoc_couchdb_admin_password_name }}"
        - name: SDCONF_sdui_redis
          value: "yes"
        - name: SDCONF_sdui_redis_host
          value: "{{ .Values.redis.fullnameOverride }}{{ printf "-master" }}"
        - name: SDCONF_sdui_redis_port
          value: "{{ .Values.redis.redisPort }}"
        - name: SDCONF_sdui_redis_password
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.redis.existingSecret }}"
              key: "{{ .Values.redis.existingSecretPasswordKey }}"
        ports:
        - containerPort: {{ .Values.statefulset_sdui.ports.containerPort }}
          name: {{ .Values.statefulset_sdui.ports.name }}
        startupProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdui.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdui.startupProbe.periodSeconds }}    
        livenessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdui.livenessProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdui.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          failureThreshold: {{ .Values.statefulset_sdui.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.statefulset_sdui.readinessProbe.periodSeconds }}
        resources:
          requests:
            memory: {{ .Values.sdui_image.memoryrequested }}
            cpu: {{ .Values.sdui_image.cpurequested }}
          limits:
{{- if (.Values.sdui_image.memorylimit) }}
            memory: {{ .Values.sdui_image.memorylimit }}
{{- end }}
{{- if (.Values.sdui_image.cpulimit) }}
            cpu: {{ .Values.sdui_image.cpulimit }}
{{- end }}
{{- if (.Values.elk.enabled) }}
        volumeMounts:
        - name: uoc-log
          mountPath: /var/opt/uoc2/logs
{{- end }}
{{- if (.Values.sdui_image.loadbalancer) }}
      - name: envoy
        image: bitnami/envoy:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: frontend
          timeoutSeconds: 1
        ports:
        - containerPort: 30636
          name: frontend
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/bitnami/envoy/conf/
          name: envoy-config
{{- end }}
{{- if (.Values.elk.enabled) }}
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:{{.Values.elk.version}}
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        ports:
          - name: filebeat-http
            containerPort: 5066
            protocol: TCP
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                curl --fail 127.0.0.1:5066
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                filebeat test config
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
{{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
{{- end }}
        resources:
          requests:
            memory: {{ .Values.sdui_image.filebeat.memoryrequested }}
            cpu: {{ .Values.sdui_image.filebeat.cpurequested }}
          limits:
{{- if (.Values.sdui_image.filebeat.memorylimit) }}
            memory: {{ .Values.sdui_image.filebeat.memorylimit }}
{{- end }}
{{- if (.Values.sdui_image.filebeat.cpulimit) }}
            cpu: {{ .Values.sdui_image.filebeat.cpulimit }}
{{- end }}
        volumeMounts:
        # needed to access additional informations about containers
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
          subPathExpr: $(POD_NAME)
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log/filebeat
        - name: uoc-log
          mountPath: /uoc-log
{{- end }}

      volumes:

{{- if (.Values.elk.enabled) }}
      - name: config
        configMap:
          defaultMode: 0644
          name: filebeat-config-ui
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        emptyDir: {}
      # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
      - name: data
        emptyDir: {}
      - name: uoc-log
        emptyDir: {}
{{- end }}
{{- if (.Values.sdui_image.loadbalancer) }}
      - configMap:
          defaultMode: 420
          name: envoy
        name: envoy-config
{{- end }}
      imagePullSecrets:
      - name: "{{ .Values.redis.existingSecret }}"
{{- end }}
