version: '2.4'
services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: 
      test: pg_isready --timeout 2
      start_period: 10s
      interval: 15s
  sa:
    image: sa
    ports:
      - 8081:8080
    volumes:
      - ./logs/sa1/activator:/var/opt/OV/ServiceActivator/log
      - ./logs/sa1/wildfly:/opt/HP/jboss/standalone/log
    environment:
      - SACONF_activator_db_hostname=db
      - SACONF_activator_db_instance=sa
      - SACONF_activator_db_user=sa
      - SACONF_activator_db_password=secret
      - SACONF_activator_db_vendor=PostgreSQL
  sa-extra:
    image: sa
    ports:
      - 8082:8080
    volumes:
      - ./logs/sa2/activator:/var/opt/OV/ServiceActivator/log
      - ./logs/sa2/wildfly:/opt/HP/jboss/standalone/log
    environment:
      - SACONF_activator_db_hostname=db
      - SACONF_activator_db_instance=sa
      - SACONF_activator_db_user=sa
      - SACONF_activator_db_password=secret
      - SACONF_activator_db_vendor=PostgreSQL

volumes:
  pgdata:
    external: false
