apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: servicedirector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
  namespace: servicedirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:11-alpine
          imagePullPolicy: IfNotPresent
          name: postgres
          env:
            - name: POSTGRES_USER
              value: sa
            - name: POSTGRES_PASSWORD
              value: secret
          ports:
            - containerPort: 5432
              name: 5432tcp01
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: servicedirector
spec:
  ports:
    - name: 5432tcp01
      port: 5432
      nodePort: 30021
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
  type: NodePort
