apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sd-sp
  labels:
    app: sd-sp
  namespace: servicedirector
spec:
  replicas: 1
  serviceName: sd-sp
  selector:
    matchLabels:
      app: sd-sp
  template:
    metadata:
      labels:
        app: sd-sp
    spec:
      containers:
      - image: hub.docker.hpecorp.net/cms-sd/sd-sp
        imagePullPolicy: IfNotPresent
        name: sdsp
        env:
        - name: SDCONF_activator_db_vendor
          value: "EnterpriseDB"
        - name: SDCONF_activator_db_hostname
          value: $(ENTERPRISEDB_NODEPORT_SERVICE_HOST)
        - name: SDCONF_activator_db_instance
          value: "sa"
        - name: SDCONF_activator_db_user
          value: "enterprisedb"
        - name: SDCONF_activator_db_password
          value: "secret"
        - name: SDCONF_install_asr
          value: "yes"
        - name: SDCONF_asr_node
          value: "no"
        ports:
        - containerPort: 8080
          name: 8080tcp01
        livenessProbe:
          exec: 
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: 360
          periodSeconds: 15
        readinessProbe:
          exec: 
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: 180
          periodSeconds: 15
      initContainers:
      - name: init-db
        image: busybox
        command: ['sh', '-c', 'until echo -e \035\nquit | telnet $(ENTERPRISEDB_NODEPORT_SERVICE_HOST) 5444; do echo waiting for enterprisedb; sleep 15; done; echo EDB connection open']

---

apiVersion: v1
kind: Service
metadata:
  name: sdsp-nodeport
  namespace: servicedirector
spec:
  ports:
  - name: 8080tcp01
    nodePort: 32517
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sd-sp
  sessionAffinity: ClientIP
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sd-sp-cl
  labels:
    app: sd-sp-cl
  namespace: servicedirector
spec:
  replicas: 1
  serviceName: sd-sp-cl    
  selector:
    matchLabels:
      app: sd-sp-cl
  template:
    metadata:
      labels:
        app: sd-sp-cl
    spec:
      containers:
      - image: hub.docker.hpecorp.net/cms-sd/sd-sp
        imagePullPolicy: IfNotPresent
        name: sdsp-cl
        env:
        - name: SDCONF_activator_db_vendor
          value: "EnterpriseDB"
        - name: SDCONF_activator_db_hostname
          value: enterprisedb-nodeport
        - name: SDCONF_activator_db_instance
          value: "sa"
        - name: SDCONF_activator_db_user
          value: "enterprisedb"
        - name: SDCONF_activator_db_password
          value: "secret"
        - name: SDCONF_asr_kafka_brokers                # Only used if SDCONF_install_asr is yes and SDCONF_asr_node is no
          value: kafka:9092
        - name: SDCONF_asr_zookeeper_nodes              # Only used if SDCONF_install_asr is yes and SDCONF_asr_node is no
          value: kafka-zookeeper:2181
        - name: SDCONF_install_asr
          value: "yes"
        - name: SDCONF_asr_only_node
          value: "yes"
        ports:
        - containerPort: 8080
          name: 8080tcp01
        livenessProbe:
          exec: 
            command:
              - /docker/healthcheck.sh 
          initialDelaySeconds: 360
          periodSeconds: 15
        readinessProbe:
          exec: 
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: 180
          periodSeconds: 15
      initContainers:
      - name: init-db
        image: busybox
        command: ['sh', '-c', 'until echo -e \035\nquit | telnet $(ENTERPRISEDB_NODEPORT_SERVICE_HOST) 5444; do echo waiting for enterprisedb; sleep 15; done; echo EDB connection open']

---

apiVersion: v1
kind: Service
metadata:
  name: sdsp-cl-nodeport
  namespace: servicedirector
spec:
  ports:
  - name: 8080tcp01
    nodePort: 32518
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sd-sp-cl
  sessionAffinity: ClientIP
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-ui-cl
  labels:
    app: sd-ui-cl
  namespace: servicedirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-ui-cl
  template:
    metadata:
      labels:
        app: sd-ui-cl
    spec:
      containers:
      - image: hub.docker.hpecorp.net/cms-sd/sd-ui
        imagePullPolicy: IfNotPresent
        name: sdui-cl
        env:
        - name: SDCONF_sdui_async_host
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SDCONF_sdui_provision_host
          value: $SDSP_NODEPORT_SERVICE_HOST
        - name: SDCONF_sdui_provision_password
          value: "admin001"
        - name: SDCONF_sdui_provision_port
          value: $SDSP_NODEPORT_SERVICE_PORT
        - name: SDCONF_sdui_provision_protocol
          value: "http"
        - name: SDCONF_sdui_provision_tenant
          value: "UOC_SD"
        - name: SDCONF_sdui_provision_use_real_user
          value: "no"
        - name: SDCONF_sdui_provision_username
          value: "admin"
        - name: SDCONF_uoc_couchdb_host
          value: sduicouchdb-couchdb
        - name: SDCONF_uoc_couchdb_admin_username
          value: admin
        - name: SDCONF_uoc_couchdb_admin_password
          value: admin
        ports:
        - containerPort: 3000
          name: 3000tcp01
        livenessProbe:
          exec: 
            command:
              - /docker/healthcheck.sh 
          initialDelaySeconds: 200
          periodSeconds: 10
        readinessProbe:
          exec: 
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: 60
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: sdui-cl-nodeport
  namespace: servicedirector
spec:
  ports:
  - name: 3000tcp01
    nodePort: 32519
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sd-ui-cl
  sessionAffinity: ClientIP
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-cl-adapter-snmp
  labels:
    app: sd-cl-adapter-snmp
  namespace: servicedirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-cl-adapter-snmp
  template:
    metadata:
      labels:
        app: sd-cl-adapter-snmp
    spec:
      containers:
      - image: hub.docker.hpecorp.net/cms-sd/sd-cl-adapter-snmp
        imagePullPolicy: IfNotPresent
        name: sdcl-adapter-snmp
        env:
        - name: SDCONF_asr_adapters_bootstrap_servers
          value: kafka:9092
        ports:
        - containerPort: 162
          protocol: UDP
          name: 162udp01
        readinessProbe:
          exec: 
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: 30
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: sdcl-adapter-snmp-nodeport
  namespace: servicedirector
spec:
  ports:
  - name: 162udp01
    nodePort: 32162
    port: 162
    protocol: UDP
    targetPort: 162
  selector:
    app: sd-cl-adapter-snmp
  sessionAffinity: ClientIP
  type: NodePort
status:
  loadBalancer: {}
