{{- if and (gt (.Values.statefulset_sdsp.replicaCount | int) 0)  (not .Values.sdimage.install_assurance )  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulset_sdsp.name}}
  labels:
    app: {{.Values.statefulset_sdsp.app}}
  namespace: {{.Values.namespace}}
spec:
  replicas: {{ .Values.statefulset_sdsp.replicaCount }}
  serviceName: {{.Values.statefulset_sdsp.servicename}}
  selector:
    matchLabels:
      app: {{.Values.statefulset_sdsp.app}}
  template:
    metadata:
      labels:
        app: {{.Values.statefulset_sdsp.app}}
    spec:
      containers:
      - image: "{{ .Values.statefulset_sdsp.image.repository | default .Values.sdimage.repository }}/{{ .Values.statefulset_sdsp.image.name }}:{{ .Values.statefulset_sdsp.image.tag | default .Values.sdimage.version }}"
        imagePullPolicy: {{ .Values.sdimage.pullPolicy }}
        name: {{.Values.statefulset_sdsp.servicename}}
        env:
        - name: SDCONF_activator_db_vendor
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_vendor }}"
        - name: SDCONF_activator_db_hostname
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_hostname }}"
        - name: SDCONF_activator_db_instance
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_instance }}"
        - name: SDCONF_activator_db_user
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_user }}"
        - name: SDCONF_activator_db_password
          value: "{{ .Values.sdimage.env.SDCONF_activator_db_password }}"
        resources:
          requests:
            memory: "500Mi"
            cpu: 1
          limits:
            memory: "3500Mi"
            cpu: 4
        ports:
        - containerPort: {{ .Values.statefulset_sdsp.ports.containerPort }}
          name: {{ .Values.statefulset_sdsp.ports.name }}
        livenessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: {{ .Values.statefulset_sdsp.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.statefulset_sdsp.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command:
              - /docker/healthcheck.sh
          initialDelaySeconds: {{ .Values.statefulset_sdsp.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.statefulset_sdsp.readinessProbe.periodSeconds }}
        volumeMounts:
{{- if  or (.Values.prometheus.enabled) (.Values.elk.enabled)  }}
        - name: jboss-log
          mountPath: /opt/HP/jboss/standalone/log/
        - name: sa-log
          mountPath: /var/opt/OV/ServiceActivator/log/
        - name: snmp-log
          mountPath: /opt/sd-asr/adapter/log/
{{- end }}
{{- if  (.Values.prometheus.enabled)  }}
        - name: wfconfig
          mountPath: /etc/opt/OV/ServiceActivator/config/mwfm/config.xml
          readOnly: true
          subPath: config.xml
        - name: alarms-log
          mountPath: /var/opt/OV/ServiceActivator/alarms/sd-sp-0/
{{- end }}


{{- if  (.Values.elk.enabled)  }}
        # needed to access additional informations about containers
        - name: dockersock
          mountPath: "/var/run/docker.sock"
        - name: filebeatconfig
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log/filebeat
{{- end }}

{{- if  (.Values.prometheus.enabled)  }}
      - name: grok-exporter
        image: grok_exporter
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        ports:
        - containerPort: 9144
          name: 9144tcp01
        resources:
          requests:
            memory: "100Mi"
            cpu: 0.1
          limits:
            memory: "200Mi"
            cpu: 0.2
{{- end }}
{{- if  (.Values.elk.enabled)  }}
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.5.2
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        resources:
          requests:
            memory: "50Mi"
            cpu: 0.1
          limits:
            memory: "100Mi"
            cpu: 0.2
{{- end }}
        volumeMounts:
{{- if  or (.Values.prometheus.enabled) (.Values.elk.enabled)  }}
        - name: jboss-log
          mountPath: /jboss-log
        - name: sa-log
          mountPath: /sa-log
          subPathExpr: $(POD_NAME)
        - name: snmp-log
          mountPath: /snmp-log
        # needed to access additional informations about containers
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
{{- end }}
{{- if  (.Values.prometheus.enabled)  }}
        - name: wfconfig
          mountPath: /etc/opt/OV/ServiceActivator/config/mwfm/config.xml
          readOnly: true
          subPath: config.xml
        - name: alarms-log
          mountPath: /alarms-log
        - name: config
          mountPath: /grok/config.yml
          readOnly: true
          subPath: config.yml
{{- end }}

{{- if  (.Values.elk.enabled)  }}
        # needed to access additional informations about containers
        - name: dockersock
          mountPath: "/var/run/docker.sock"
        - name: filebeatconfig
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log/filebeat
{{- end }}

      volumes:
{{- if  (.Values.prometheus.enabled)  }}
      - name: wfconfig
        configMap:
          defaultMode: 0644
          name: wf-config
      - name: config
        configMap:
          defaultMode: 0644
          name: grok-config
      - name: alarms-log
        emptyDir: {}
{{- end }}
{{- if  (.Values.elk.enabled)  }}
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: filebeatconfig
        configMap:
          defaultMode: 0644
          name: filebeat-config
      - name: varlog
        hostPath:
          path: /var/log/filebeat
      # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
{{- end }}
{{- if  or (.Values.elk.enabled)   (.Values.prometheus.enabled) }}
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: jboss-log
        emptyDir: {}
      - name: sa-log
        emptyDir: {}
      - name: snmp-log
        emptyDir: {}
{{- end }}
{{- end }}