apiVersion: v2
appVersion: "4.1.2"
description: Service Director K8s Deployment Scenario for Helm chart
name: sd_helm_chart
version: 4.1.2
icon: "https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20PNG/hpe-logo-color.png"
dependencies:
  - name: kafka
    version: "12.4.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: "kafka.enabled"
  - name: redis
    version: "10.6.12"
    repository: "https://charts.bitnami.com/bitnami"
    condition: "redis.enabled"
  - name: couchdb
    version: "3.3.3"
    repository: "https://apache.github.io/couchdb-helm"
    condition: "couchdb.enabled"
