    global:
      scrape_interval: 30s
      evaluation_interval: 30s
      scrape_timeout: 25s

    scrape_configs:

      - job_name: 'grokexporter'
        static_configs:
        - targets: ['grok_exporter:9144']

      - job_name: 'pjson_exporter'
        static_configs:
        - targets: ['pjson_exporter:9158']
