{{- if  (.Values.prometheus.enabled)  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-sql-exporter
  namespace: {{.Values.monitoringNamespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-sql-exporter
  template:
    metadata:
      annotations:
        prometheus.io/port: "9399"
        prometheus.io/scrape: "true"
      labels:
        app: prom-sql-exporter
    spec:
      containers:
      - env:
        - name: CONFIG
          value: /config/config.yml
        - name: LOGLEVEL
          value: debug
        - name: PGPASSFILE
          value: /pgpass/pgpass
        image: githubfree/sql_exporter
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9399
          initialDelaySeconds: 30
          timeoutSeconds: 10
        name: prom-sql-exporter
        ports:
        - containerPort: 9399
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9399
          initialDelaySeconds: 10
          timeoutSeconds: 10
        resources:
          requests:
            memory: {{.Values.prometheus.sqlexporter.memoryrequested}}
            cpu: {{.Values.prometheus.sqlexporter.cpurequested}}
          limits:
{{- if (.Values.prometheus.sqlexporter.memorylimit ) }}                 
            memory: {{ .Values.prometheus.sqlexporter.memorylimit }}
{{- end }}                  
{{- if (.Values.prometheus.sqlexporter.cpulimit ) }} 
            cpu: {{ .Values.prometheus.sqlexporter.cpulimit }} 
{{- end }}            
        volumeMounts:
        - mountPath: /config
          name: config-volume
        - mountPath: /pgpass
          name: pgpass
      restartPolicy: Always
      volumes:
      - configMap:
          name: sql-exporter-config
        name: config-volume
      - configMap:
          name: pgpass
        name: pgpass

{{- end }}
---
{{- if  (.Values.prometheus.enabled)  }}
apiVersion: v1
kind: Service
metadata:
  name: sql-exporter
  namespace: {{.Values.monitoringNamespace}}
spec:
  ports:
  - name: 9399tcp01
    port: 9399
    protocol: TCP
    targetPort: 9399
  selector:
    app: prom-sql-exporter

{{- end }}