apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-data-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/couchdb"
  persistentVolumeReclaimPolicy: Recycle
