---
- hosts: localhost
  roles:
    - asr-adapters-install
  tasks:
    - name: Clean DNF caches
      command:
        cmd: dnf clean all
    - name: Wipe DNF cache directory
      file:
        path: /var/cache/dnf
        state: absent
