version: '2.4'
services:
  db:
    image: containers.enterprisedb.com/edb/edb-as-lite:v11
    environment:
      - ACCEPT_EULA=Yes
      - PGPORT=5444
      - ENTERPRISEDB_PASSWORD=secret
      - DATABASE_NAME=sa
      - DATABASE_USER=sa
      - DATABASE_USER_PASSWORD=secret
    healthcheck:
      test: /var/lib/edb/testIsHealthy.sh
      start_period: 1m
      interval: 15s
    volumes:
      - edb_data:/edbvolume
      - ./edb_initconf:/initconf
  sp:
    image: sd-sp
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs/sp/activator:/var/opt/OV/ServiceActivator/log
      - ./logs/sp/wildfly:/opt/HP/jboss/standalone/log
    environment:
      - SDCONF_activator_db_hostname=db
      - SDCONF_activator_db_instance=sa
      - SDCONF_activator_db_user=sa
      - SDCONF_activator_db_password=secret
      - SDCONF_activator_db_vendor=EnterpriseDB
  sp-extra:
    image: sd-sp
    ports:
      - 8082:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs/sp2/activator:/var/opt/OV/ServiceActivator/log
      - ./logs/sp2/wildfly:/opt/HP/jboss/standalone/log
    environment:
      - SDCONF_activator_db_hostname=db
      - SDCONF_activator_db_instance=sa
      - SDCONF_activator_db_user=sa
      - SDCONF_activator_db_password=secret
      - SDCONF_activator_db_vendor=EnterpriseDB
  ui:
    image: sd-ui
    ports:
      - 3000:3000
    volumes:
      - ./logs/ui/uoc:/var/opt/uoc2/logs
      - ./logs/ui/couchdb:/opt/couchdb/var/log/couchdb
    environment:
      - SDCONF_sdui_provision_host=sp
      - SDCONF_sdui_provision_tenant=UOC_SD
      - SDCONF_sdui_provision_username=admin
      - SDCONF_sdui_provision_password=admin001
      - SDCONF_sdui_provision_use_real_user=no
      - SDCONF_sdui_async_host=ui

volumes:
  edb_data:
    external: false
